<?php
?>
<form id="forgotForm" action = "<?=$this->url('home/forgotPassword')?>"
      data-bing-action-uri="#" data-form-code="KPGSF" target="_self" method="GET">
	<div class="ForgotForm">

		<label style="display: block;"><?=$this->translate('email utilizator')?></label>
		<input type="email" style="width:100%;"
               maxlength="250" value="" spellcheck="false" autocomplete="off"
               name="email">

	</div>
	<div class="">
		<a id="forgotButton" class="btn-green" href="javascript:;" onclick="$('#forgotForm').submit()">Resetare Parola</a>
		<br /><input type="submit" style="float: right;visibility: hidden;">
	</div>

</form>

<a href="javascript:;" id="loginTab">Log in</a>