<?php
//$this->layout()->js_call .= ' generalObj.loginRegister.init(); ';
$emailValue = '';
?>
<form id="registerForm" data-bing-action-uri="<?php echo $this->url('home/register'); ?>" data-form-code="KPGSF"
      target="_self" action="<?php echo $this->url('home/register'); ?>" method="POST"
      data-login-action="<?php echo $this->url('home/login'); ?>">
	<div class="loginForm registerForm">

		<label for="globalRegisterFieldEmail" style="display: block;">
            <?php echo $this->translate('email utilizator'); ?>
        </label>
		<input name="email" type="email" style="width:100%;" maxlength="250"
               value="<?=$emailValue?>" spellcheck="false" autocomplete="off" accesskey="S" tabindex="1"
               id="globalRegisterFieldEmail">
	</div>

	<div class="loginForm registerForm">

		<label for="globalRegisterFieldPass" style="display: block;"><?php echo $this->translate('parola'); ?></label>
		<input name="password" type="password" style="width:100%;" maxlength="250" value="" spellcheck="false"
               autocomplete="off" accesskey="S" tabindex="1"
               id="globalRegisterFieldPass">
	</div>


	<div class="loginForm registerForm">

		<label for="globalRegisterFieldRePass" style="display: block;"><?php echo $this->translate('confirma parola'); ?></label>
		<input name="passwordVerify" type="password" style="width:100%;" maxlength="250" value="" spellcheck="false"
               autocomplete="off" accesskey="S" tabindex="1"
               id="globalRegisterFieldRePass">
	</div>

	<div class="loginButtons registerForm">
        <a id="registerButton" href="javascript:;" onclick="$('#registerForm').submit()" class="btn btn-primary"><?=$this->translate('Creeaza Cont')?></a>
		<br /><input type="submit" style="float: right;visibility: hidden;">
	</div>

</form>

<a href="javascript:;" id="loginTab">ai cont? login</a>

<div id = "registerSocialContainer" class="socialLogin">

    <a href="/user/login/facebook" id="loginOptionFacebook" class="cellBtn rotX180 autoExecCenter">
        sau inregistreaza-te cu FaceBook
        <img class="facebook" src="<?=$this->basePath('/img/facebookLogin.png')?>" />
    </a>

</div>

