<h3><?=$this->title?></h3>
<div class="panel card card-1">
    <div class="panel-body">
    <?php
        \Application\View\Helper\Forms::render(
            $this,
            $this->form,
            $this->url('home/ad/create', ['id'=>$this->id]),
            [
                'label_size' => 'col-lg-2 col-md-2 col-sm-2 col-xs-12',
                'input_size' => 'col-lg-10 col-md-10 col-sm-10 col-xs-12',
        //        'formButtonsAlign' => 'pull-right'

            ]
        );
        ?>
    </div>
</div>