<h3><?=$this->title?></h3>

    <?php if ($this->adList !== null) { ?>
        <?=$this->adList?>
        <?=
        $this->paginationControl(
            $this->ads,
            'Sliding',
            'application/partials/list_pagination.phtml',
            ['route' => 'home/ad/myAds', 'routeArray' => ['status' => $this->statusParam]]
        );
        ?>
    <?php } else { ?>
        <p>Nu ai niciun anunt!</p>
    <?php } ?>