<h3>Anunturi</h3>

<h4><?=$this->breadcrump?></h4>

<!--Categoria si Marca-->
<div class="row">
    <div class="col-md-3">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">
                    Categoria
                </h3>
            </div>
            <div class="panel-body">
                <?=$this->layout()->cars['categories'][$this->carcategoriesId]?>
                -
                <a href="#" id="changeCarMakeButton">schimba</a>
                <div id="allCarsContainer" style="display: none">
                    <?php foreach ($this->layout()->cars['categories'] as $categoriesId=>$categories) { ?>
                    <a href="<?=$this->carCollection->urlizeCarcategories($categoriesId)?>"><?=$categories?></a>
                    <?php } ?>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-3">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">
                    Marca
                </h3>
            </div>
            <div class="panel-body">
            <?php if (($this->class) === null) { ?>
                <?php
                foreach ($this->layout()->cars['categ'][$this->carcategoriesId] as $categ) {
                    ?><a href="<?=$this->carCollection->urlizeCarClass($this->carcategoriesId, $categ)?>"><?=$categ?></a>, <?php
                }
                ?>
            <?php } else { ?>
                <?=$this->class?>
                -
                <a href="<?=$this->carCollection->urlizeCarcategories($this->carcategoriesId)?>">schimba</a>
            <?php } ?>
            </div>
        </div>
    </div>
</div>
<!--end Categoria si Marca-->

<?php if ($this->carModelId !== null && $this->adView === null) { ?>

    <!--Filtrare Anunturi-->
    <div class="row">
        <div class="col-md-12" style="padding-bottom: 20px">
            <form class="form-inline" id="searchAds" method="get" action="<?=$this->carCollection->urlizeSearchAds($this->carcategoriesId, $this->carModelId)?>">
                <div class="input-group">

                    <div class="form-group">
                        <input id ="searchInput" value="<?=$this->searchValues['input']?>" size="50" maxlength="50" class="form-control" type="text">

                        <select class="form-control" id="searchYear">
                            <option value="0">orice an</option>
                            <?php foreach ($this->years as $year) {?>
                                <option value="<?=$year?>"<?=($year == $this->searchValues['year'] ? 'selected' : '')?>><?=$year?></option>
                            <?php }?>
                        </select>


                    </div>
                    <span class="input-group-btn">
                        <button type="submit" class="btn btn-default">Cauta!</button>
                    </span>
                </div>
            </form>
        </div>
    </div>
    <!--end Filtrare Anunturi-->

    <!--Listing Anunturi-->
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">
                Anunturi Piese
            </h3>
        </div>
        <div class="panel-body">
            <?php if ($this->adList !== null) { ?>
                <?=$this->adList?>
                <?=
                $this->paginationControl(
                    $this->ads,
                    'Sliding',
                    'application/partials/list_pagination.phtml',
                    $this->carCollection->urlizePageListAds($this->carcategoriesId, $this->carModelId, null)
                );
                ?>
            <?php } else { ?>
                <p>Nu sunt anunturi in aceasta categorie</p>
            <?php } ?>
        </div>
    </div>
    <!--end Listing Anunturi-->

<?php } elseif ($this->carModelId !== null && $this->adView !== null) { ?>

    <!--Pagina Anunt-->
    <?=$this->adView?>
    <!--end Pagina Anunt-->

<?php } ?>