<?php
$cars = $this->layout()->cars;
//var_dump($this->class);
//die();
?>

<?php if (($this->class) === null) { ?>
    <?php $this->layout()->setVariable('isCategoryPage', true); ?>

    <!--Category-->
    <?=
    $this->partial(
        'application/ad/partials/categoriesBox.phtml',
        [
            'carCollection' => $this->carCollection,
            'carcategoriesId' => $this->carcategoriesId
        ]
    )?>
    <!--end Category-->

<?php } ?>

<!--Marca-->
<div class="row" style="padding-top: 70px">
    <?php
    // listare toate marcile inainte de a fi selectat modelul
    if (($this->class) === null) { ?>
        <?php $this->layout()->headTitle = 'Anunturi Gratuite - piese '.$cars['categories'][$this->carcategoriesId];?>
        <div class="col-md-12 car-brand">
            <h3>Alegeti o marca</h3>
            <div class="row popular-brands">
                <?php
                foreach ($cars['model'][$this->carcategoriesId] as $modelId=>$model) {
                    if ($model['popular']) {
                        $modelName = $model['categ'];
                        $modelNameUrlized = strtolower($this->carCollection->getUrlize($modelName));
                        ?>
                        <div class="col-md-2 col-sm-6 col-xs-6">
                            <div class="brand card card-1">
                                <a href="<?= $this->carCollection->urlizeCarClass($this->carcategoriesId, $modelName) ?>"
                                    title="Piese <?=$cars['categories'][$this->carcategoriesId]?> <?= $modelName ?>">
                                    <?php if (is_file(PUBLIC_IMG_PATH.'/../img/brand/'.$modelNameUrlized.'.jpg')) { ?>
                                        <img class="img-responsive" src="<?=$this->basePath() . '/img/brand/'.$modelNameUrlized.'.jpg'?>"/></a>
                                    <?php } else { ?>
                                    <h3 style="width: 100%"><?= $modelName ?></h3>
                                    <?php } ?>
                                </a>
                            </div>
                        </div><?php
                    }
                }
                ?>
            </div>
            <div class="car-brand-list card card-1">
                <?php $cnt = 0;
                $splitVal = floor(count($cars['model'][$this->carcategoriesId]) / 6) + 1;
                foreach ($cars['model'][$this->carcategoriesId] as $modelId=>$model) {

                    if ($cnt % $splitVal == 0) {
                        ?><div class="col-md-2 col-sm-6 col-xs-12"><?php
                    }
                    ?>
                    <span></span>
                    <a
                       title = "Piese <?=$cars['categories'][$this->carcategoriesId]?> <?= $model['categ'] ?>"
                       href="<?=$this->carCollection->urlizeCarClass($this->carcategoriesId, $model['categ'])?>">
                        <?=$model['categ']?>
                    </a><br>
                    <?php
                    if ($cnt % $splitVal == $splitVal - 1) {
                        ?></div><?php
                    }
                    $cnt++;
                }
                if (($cnt-1) % $splitVal == $splitVal - 1) {
                    ?></div><?php
                }
                ?>
            </div>
        </div>
    <?php } else {
        // listare categorie + model
        ?>
        <div class="change-categories col-sm-4 col-md-3">
            <a href="javascript:;" class="panel card card-1" id="changeCarMakeButton">
                <img src="<?=$this->basePath()?>/img/categ_<?=$this->carcategoriesId?>.png" />
                <?=$this->class?>
                <span class="arrow"></span>
            </a>

        </div>
        <div class="col-md-12 change-categories" id="allCarsContainer" style="display: none">
            <?php foreach ($cars['categories'] as $categoriesId=>$categories) { ?>
                <div class="row">
                    <div class="change-categories col-md-3">
                        <a class="panel card card-1"
                           title = "Piese <?=$cars['categories'][$categoriesId]?>"
                           href="<?=$this->carCollection->urlizeCarcategories($categoriesId)?>">
                            <img src="<?=$this->basePath()?>/img/categ_<?=$categoriesId?>.png" />
                            <?=$categories?>
                        </a>
                    </div>
                    <div class="col-md-9">
                        <div class="row popular-brands">
                            <?php
                            foreach ($cars['model'][$categoriesId] as $modelId=>$model) {
                                if ($model['popular']) {
                                    $modelName = $model['categ'];
                                    $modelNameUrlized = strtolower($this->carCollection->getUrlize($modelName));
                                    ?>
                            <div class="col-md-2 col-sm-6 col-xs-6">
                                <div class="brand card card-1">
                                    <a title = "Piese <?=$cars['categories'][$categoriesId]?> <?= $modelName ?>"
                                       data-page-load="ajax"
                                       href="<?= $this->carCollection->urlizeCarClass($categoriesId, $modelName) ?>">
                                        <?php if (is_file(PUBLIC_IMG_PATH.'/../img/brand/'.$modelNameUrlized.'.jpg')) { ?>
                                            <img class="img-responsive" src="<?=$this->basePath() . '/img/brand/'.$modelNameUrlized.'.jpg'?>"/></a>
                                        <?php } else { ?>
                                            <h3><?= $modelName ?></h3>
                                        <?php } ?>
                                    </a>
                                </div>
                            </div>
                            <?php } ?>
                        <?php }
                            ?>
                        </div>
                    </div>
                </div>
            <?php } ?>

        </div>
    <?php } ?>
</div>
<!--end Marca-->

<?php if ($this->carModelId !== null && $this->adView === null) { ?>
<div class="row">
    <div class="col-sm-4 col-md-3 filters">
    <h3>Cautare</h3>
    <!--Filtrare Anunturi-->
        <form class="panel col-md-12 card card-1" id="searchAds" method="get" action="<?=$this->carCollection->urlizeSearchAds($this->carcategoriesId, $this->carModelId)?>">
            <div class="key-words">
                <label>Cuvinte cheie</label>
                <input id ="searchInput" value="<?=$this->searchValues['input']?>"  maxlength="50"  type="text">
            </div>
            <div class="row">
                <div class="col-xs-6">
                <label>An fabricatie</label>
                <select  id="searchYear">
                    <option value="">orice an</option>
                    <?php foreach ($this->years as $year) {?>
                        <option value="<?=$year?>" <?=($year == $this->searchValues['year'] ? 'selected' : '')?>><?=$year?></option>
                    <?php }?>
                </select>
                </div>
            <div class="col-xs-6">
                <label>Stare piesa</label>
                <select id="searchStare">
                    <option value="" <?=('' == $this->searchValues['stare'] ? 'selected' : '')?>>oricare</option>
                    <option value="nou" <?=('nou' == $this->searchValues['stare'] ? 'selected' : '')?>>Noua</option>
                    <option value="second" <?=('second' == $this->searchValues['stare'] ? 'selected' : '')?>>Second</option>
                </select>
            </div>
            </div>
            <div class="row">
            <div class="col-xs-6">
                <label>Judet</label>
                <select id="searchCounty">
                    <?php foreach ($this->states as $k=>$state) { ?>
                        <option value="<?=$k?>" <?=($k == $this->searchValues['county'] ? 'selected' : '')?>><?=$state?></option>
                    <?php } ?>
                </select>
            </div>
            <div class="col-xs-6">
                <label>Cod piesa</label>
                <input id ="searchOem" value="<?=$this->searchValues['oem']?>"  maxlength="50"  type="text">
            </div>
            </div>
            <button type="submit" id="button-search-ads" class="btn-green button" data-loading-text="cautare...">cauta</button>
        </form>
<!--end Filtrare Anunturi-->

<!-- reclame -->
        <?=
        $this->partial(
            'application/ad/partials/partners.phtml',
            []
        )?>
<!-- end reclame -->
    </div>

<!--Listing Anunturi-->  
    <div id="announcement-listing" class="col-sm-8 col-md-9 brand-listing">
        <?php $this->layout()->headTitle = 'Anunturi Piese de '.$cars['categories'][$this->carcategoriesId] . ' ' . $this->class; ?>
        <h3 id="pageTitleElement"><?=$this->layout()->headTitle?></h3>
        <?php if ($this->adList !== null) { ?>
            <?=$this->adList?>
            <?=
            $this->paginationControl(
                $this->ads,
                'Sliding',
                'application/partials/list_pagination.phtml',
                $this->carCollection->urlizePageListAds($this->carcategoriesId, $this->carModelId, null)
            );
            ?>
        <?php } else { ?>
            <span class="no-results-found">
                Nu am gasit anunturi in aceasta categorie.
            </span>
            <a href="<?=$this->url('home/offers/create')?>" class="btn-red button pull-right">Cere oferta</a>
        <?php } ?>
    </div>
</div>
    <!--end Listing Anunturi-->

<?php } elseif ($this->carModelId !== null && $this->adView !== null) { ?>

    <!--Pagina Anunt-->
    <?=$this->adView?>
    <!--end Pagina Anunt-->

    <!-- anunturi related-->
    <div class="row">
        <h3 class="col-md-12 new">Anunturi asemanatoare</h3>
        <div class="col-md-9">
            <?= $this->relatedAds ?>
        </div>
        <div class="col-md-3">
            <?=
            $this->partial(
                'application/ad/partials/partners.phtml',
                []
            )?>
        </div>
    </div>
    <!-- end anunturi related -->

<?php } ?>
