<?php
$this->headLink()
    ->prependStylesheet('/jquery-file-upload/blueimp-gallery/blueimp-gallery.min.css')
;
$this->headScript()
    ->appendFile('/jquery-file-upload/blueimp-gallery/jquery.blueimp-gallery.min.js', 'text/javascript')
;
?>
<?php if ($this->status !== 'ok') { ?>
    <div class="alert alert-info alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        Anuntul a expirat!
    </div>
<?php } ?>

<div class="product-details">
        <h3>
            <?= $this->title ?> pentru <?= $this->car['class'] ?>
        </h3>
        <div class="info-dates">
            <span><span class="glyphicon glyphicon-eye-open"></span>Vizualizari:<?=$this->views?></span>
            <span><span class="glyphicon glyphicon-calendar"></span>Expira la <?=$this->expirationDate?></span>
            <span><span class="glyphicon glyphicon-refresh"></span>Actualizat la <?=$this->refreshDate?></span>
        </div>
    <div class="product-images panel">
        <?php
            if (count($this->images) > 0) {
                $img = $this->images[0];
            } else {
                $img = 0;
            }
            ?>
                <div class="big-image">
                    <a href="<?=
                    \Application\libs\General::getSimpleAvatar(
                        $this->folder,
                        $img,
                        '2000x2000'
                    ) ?>" type="" title="" download="" data-image-lib="popup">
                        <img class="img-responsive" src="<?=
                        \Application\libs\General::getSimpleAvatar(
                            $this->folder,
                            $img,
                            '900x500'
                        ) ?>">
                    </a>
                </div>

                <div class="row tumb-img">
                <?php
                if (count ($this->images) > 0) {
                    foreach ($this->images as $k=>$img) { if ($k>=0) { ?>
                    <div class="col-xs-3" style="padding-top: 15px;<?=($k>4 ? ' display:none; ' : '')?>">
                        <a href="<?=
                        \Application\libs\General::getSimpleAvatar(
                            $this->folder,
                            $img,
                            '2000x2000'
                        ) ?>" type="" title="" download="" data-image-lib="popup">
                            <img class="img-responsive" src="<?=
                            \Application\libs\General::getSimpleAvatar(
                                $this->folder,
                                $img,
                                '150x100'
                            ) ?>">
                        </a>
                    </div>    
                <?php } } } ?>
                </div>
        </div>
        
    <div class="product-info panel">
        <div class="seller">
            <span>Vanzator</span>
            <h4><?=$this->advertiser['name']?></h4>
            <a href="http://<?=$this->advertiser['url']?>"><?=$this->advertiser['url']?></a>
        </div>
        <div class="price-box">
            <span class="price"><?=$this->price?></span>
            <span class="stare"><?=($this->stare == 'nou' ? $this->translate('Nou') : $this->translate('Second'))?></span>
        </div>
        <div class="info-details">
            <p>
                <span class="category-icon">
                    <img src="<?=$this->basePath()?>/img/<?=$this->car['categoryImg']?>.png" />
                </span>
                <span><?=$this->car['category']?></span>
            </p>
            <p>
                <span class="car-brand-icon">

                    <?php if (is_file(PUBLIC_IMG_PATH.'/../img/brand/'.$this->car['classUrlized'].'.jpg')) { ?>
                        <img src="<?=$this->basePath() . '/img/brand/'.$this->car['classUrlized'].'.jpg'?>"/></a>
                    <?php } else { ?>
                        <img src="<?=$this->basePath()?>/img/<?=$this->car['categoryImg']?>.png" />
                    <?php } ?>

                </span>
                <span><?=$this->car['class']?> <?=$this->car['model']?></span>
            </p>
           <?php /*<p>Stare: <?=$this->stare?></p>*/ ?>
            <p><span class="glyphicon glyphicon-calendar" style="padding: 0 6px"></span> <span>2013 - 2015</span></p>
            <p>Cod Piesa: <span><?=$this->car['oem']?></span></p>
            <p class="description"><?= $this->description ?></p>

        </div>
        <div class="contact">
            <div id = "contactParkContainer" style="display: none">
                Telefon: <span id="contactParkPhone"></span><br />
                Email: <span id="contactParkEmail"></span><br />
                Adresa: <span id="contactParkAddress"></span><br />
            </div>
            <a id="adGetContactButton" href="javascript:;" role="button" class="btn-green"
               data-loading-text="se incarca..."
               style="padding: 20px; width: 100%">Contacteaza vanzator</a>
        </div>
    </div>   
</div>


<!-- The blueimp Gallery widget -->
<div id="blueimp-gallery" class="blueimp-gallery blueimp-gallery-controls" data-filter="">
    <div class="slides">
    </div>
    <h3 class="title"></h3>
    <a class="prev">
        ‹
    </a>
    <a class="next">
        ›
    </a>
    <a class="close white">
    </a>
    <a class="play-pause">
    </a>
    <ol class="indicator">
    </ol>
</div>