<?php
$this->headLink()
    ->prependStylesheet('/jquery-file-upload/blueimp-gallery/blueimp-gallery.min.css')
;
$this->headScript()
    ->appendFile('/jquery-file-upload/blueimp-gallery/jquery.blueimp-gallery.min.js', 'text/javascript')
;
?>
<?php if ($this->status !== 'ok') { ?>
    <div class="alert alert-info alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        Anuntul a expirat!
    </div>
<?php } ?>

<div class="product-details row">
        <h3>
            <?= $this->title ?> pentru <?= $this->car['class'] ?>
        </h3>
    <div class="product-images col-md-8">
        <div class="col-md-12 panel">
        <?php
            if (count($this->images) > 0) {
                $img = $this->images[0];
            } else {
                $img = 0;
            }
            ?>
                <a href="<?=
                \Application\libs\General::getSimpleAvatar(
                    $this->folder,
                    $img,
                    '2000x2000'
                ) ?>" type="" title=""
                   download="" data-gallery>
                    <img class="img-responsive" src="<?=
                    \Application\libs\General::getSimpleAvatar(
                        $this->folder,
                        $img,
                        '300x300'
                    ) ?>">
                </a>
                <?php
            if (count ($this->images) > 0) {
                foreach ($this->images as $img) { ?>
                <div class="col-md-4" style="padding-top: 15px">
                    <a href="<?=
                    \Application\libs\General::getSimpleAvatar(
                        $this->folder,
                        $img,
                        '2000x2000'
                    ) ?>" type="" title=""
                       download="" data-gallery>
                        <img class="img-responsive" src="<?=
                        \Application\libs\General::getSimpleAvatar(
                            $this->folder,
                            $img,
                            '70x70'
                        ) ?>">
                    </a>

                </div>
            <?php } } ?>
            </div>
            
            
      </div>
        
    <div class="product-info panel col-md-4">
        <div class="seller">
            <h4><?=$this->advertiser['name']?></h4>
            <a href="<?=$this->advertiser['url']?>"><?=$this->advertiser['url']?></a>
        </div>
        <p>Masina: <?=$this->car['category']?> <?=$this->car['class']?></p>
        <p>Model: <?=$this->car['class']?></p>
        <p>Stare: <?=$this->stare?></p>
        <p><?= $this->description ?></p>
        <div class="contact">
            <div id = "contactParkContainer" style="display: none">
                Telefon: <span id="contactParkPhone"></span><br />
                Email: <span id="contactParkEmail"></span><br />
                Adresa: <span id="contactParkAddress"></span><br />
            </div>
            <a id="adGetContactButton" href="javascript:;" role="button" class="btn-green"
               data-loading-text="se incarca..."
               style="padding: 20px; width: 100%">Vezi date de contact!</a>
        </div>
    </div>   
</div>


<!-- The blueimp Gallery widget -->
<div id="blueimp-gallery" class="blueimp-gallery blueimp-gallery-controls" data-filter="">
    <div class="slides">
    </div>
    <h3 class="title"></h3>
    <a class="prev">
        ‹
    </a>
    <a class="next">
        ›
    </a>
    <a class="close white">
    </a>
    <a class="play-pause">
    </a>
    <ol class="indicator">
    </ol>
</div>