<?php echo $this->doctype();

$role = $this->authenticatedUserRole();
$user = $this->zfcUserIdentity() ? $this->zfcUserIdentity() : null;

?><html lang="ro-RO">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <?php
    $this->headTitle()->append($this->headTitle)->setSeparator(' - ')->append('Tirbox.ro');
    echo $this->headTitle()->setAutoEscape(false)
    ?>
    <meta name="robots" content="index, follow" />
    <meta http-equiv="Content-Language" content="ro" />
    <link href="http://www.tirbox.ro" hreflang="ro" rel="alternate" title="Tirbox" type="text/html"/>
    <link rel="canonical" href="http://tirbox.ro" />

    <?php echo $this->headMeta()
        ->appendName('description', $this->metaDescription)
        ->appendName('keywords', $this->metaKeywords)
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?php
    echo $this
        ->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
        ->prependStylesheet($this->basePath() . '/css/style.css?v'.TBVER)
        ->prependStylesheet($this->basePath() . '/assets/jquery-file-upload/blueimp-gallery/blueimp-gallery.min.css')
        ->prependStylesheet($this->basePath() . '/js/nprogress-master/nprogress.css')
//            ->prependStylesheet($this->basePath() . '/css/select2/select2.min.css')

        ->prependStylesheet('http://fonts.googleapis.com/css?family=Ubuntu:400,300,500,700')
        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
        ->prependStylesheet($this->basePath() . '/css/reset.css')
    ;
    ?>

    <!-- Scripts -->
    <?php echo $this->headScript()
        ->appendFile($this->basePath() . '/assets/jquery-file-upload/blueimp-gallery/jquery.blueimp-gallery.min.js', 'text/javascript')
        ->prependFile($this->basePath() . '/js/nprogress-master/nprogress.js')
        ->prependFile($this->basePath() . '/js/general.js?v'.TBVER)
        ->prependFile($this->basePath() . '/js/bootbox/bootbox.min.js')
//            ->prependFile($this->basePath() . '/js/select2/select2.full.js')
        ->prependFile($this->basePath() . '/js/bootstrap.min.js')
        ->prependFile($this->basePath() . '/js/jquery.min.js')

//            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
//            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
    ; ?>

    <script>
        <?=$this->layout()->googleAnalitics?>
    </script>

    <?php if (APPLICATION_ENV != 'development') { ?>
    <!-- Hotjar Tracking Code for www.tirbox.ro -->
    <script>
        (function(h,o,t,j,a,r){
            h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
            h._hjSettings={hjid:660581,hjsv:6};
            a=o.getElementsByTagName('head')[0];
            r=o.createElement('script');r.async=1;
            r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
            a.appendChild(r);
        })(window,document,'https://static.hotjar.com/c/hotjar-','.js?sv=');
    </script>
    <?php } ?>
</head>
<body>
    <?php if (APPLICATION_ENV != 'development') { // not working - it sais is depricated ... dont know how ?>
        <div id="fb-root"></div>
        <script>
            window.fbAsyncInit = function() {
                FB.init({
                    appId      : '839888486066952',
                    xfbml      : true,
                    version    : 'v2.10'
                });
                FB.AppEvents.logPageView();
            };

            (function(d, s, id){
                var js, fjs = d.getElementsByTagName(s)[0];
                if (d.getElementById(id)) {return;}
                js = d.createElement(s); js.id = id;
                js.src = "//connect.facebook.net/en_US/sdk.js";
                fjs.parentNode.insertBefore(js, fjs);
            }(document, 'script', 'facebook-jssdk'));
        </script>
    <?php } ?>
    <script>
        NProgress.set(0.5);
        NProgress.inc(0.2);
    </script>
    <?php if (!$this->mobileApp) { ?>
    <header>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <a id ="showSearchAnnouncements" href="javascript;">
                        <span class="glyphicon glyphicon-search"></span> filtre
                    </a>
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>">
                        <img src="<?=$this->basePath() . '/img/logo-header.png'?>" alt="tirbox.ro" /><?php // echo $this->translate('tirbox.ro') ?>
                    </a>
                </div>
                <div class="collapse navbar-collapse">
                    <div class="navbar-collapse collapse" id="navbar">
                        <a class="btn-red button offersButton" style="margin:20px 0 0 20px" href="<?=$this->url('home/offers/create')?>"><?php echo $this->translate('Cerere Oferta') ?></a>
                        <ul class="nav navbar-nav navbar-right">
                            <li>
                                <a href="<?=$this->url('home')?>"><?php echo $this->translate('Acasa') ?></a>
                            </li>
                            <!--  <li>
                                <a href="#"><?php echo $this->translate('Categorii') ?></a>
                            </li> -->
                            <li>
                                <a href="<?=$this->url('home/contact')?>"><?php echo $this->translate('Contact') ?></a>
                            </li>
                            <li class="__showMobileMenu__"><a href="<?=$this->url('home/offers/create')?>">Cerere Oferta</a></li>
                            <?php if ($role == 'guest') { ?>
                                <li>
                                    <a href="<?=$this->url('home/login')?>"><?php echo $this->translate('Login') ?></a>
                                </li>

                            <?php } else { ?>
                                <li><a href="<?=$this->url('home/myAccount')?>">Contul meu</a></li>
                                <li class="__showMobileMenu__"><a href="<?=$this->url('home/ad/create')?>">Adauga anunt</a></li>
                                <li class="__showMobileMenu__"><a href="<?=$this->url('home/ad/myAds', ['status'=>'active'])?>">Anunturi active</a></li>
                                <li class="__showMobileMenu__"><a href="<?=$this->url('home/ad/myAds', ['status'=> 'inactive'])?>">Anunturi inactive</a></li>
                                <li class="__showMobileMenu__">
                                    <a href="<?=$this->url('zfcuser/logout')?>">Logout</a>
                                </li>
                            <?php } ?>
                            <li><a class="add-offer" href="<?=($role == 'guest' ? $this->url('home/login') : $this->url('home/ad/create'))?>">Adauga Anunt</a></li>
                        </ul>
                    </div>
                </div><!--/.nav-collapse -->
            </div>
        </nav>
    </header>
    <?php } ?>


    <?= $this->partial('application/ad/partials/slider.phtml', [])?>

    <div id = "mainContainer" class="container <?php if (!$this->mobileApp && !isset($this->isHomePage) && !isset($this->isCategoryPage)) { ?>mt100<?php } ?>">

        <?php
        if (count($this->flashMessenger()->getErrorMessages())) : ?>
            <div class="alert alert-danger alert-dismissable">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                <?php foreach ($this->flashMessenger()->getErrorMessages() as $fMessage) : ?>
                    <?php echo $fMessage . '<br />'; ?>
                <?php endforeach; ?>
            </div>
        <?php endif; ?>

        <?php
        if (count($this->flashMessenger()->getSuccessMessages())) : ?>
            <div class="alert alert-success alert-dismissable">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                <?php foreach ($this->flashMessenger()->getSuccessMessages() as $fMessage) : ?>
                    <?php echo $fMessage . '<br />'; ?>
                <?php endforeach; ?>
            </div>
        <?php endif; ?>


        <?php
        if (count($this->flashMessenger()->getInfoMessages())) : ?>
            <div class="alert alert-info alert-dismissable">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                <?php foreach ($this->flashMessenger()->getInfoMessages() as $fMessage) : ?>
                    <?php echo $fMessage . '<br />'; ?>
                <?php endforeach; ?>
            </div>
        <?php endif; ?>

        <?php
        if (count($this->flashMessenger()->getMessages())) : ?>
            <div class="alert alert-info alert-dismissable">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                <?php foreach ($this->flashMessenger()->getMessages() as $fMessage) : ?>
                    <?php echo $fMessage . '<br />'; ?>
                <?php endforeach; ?>
            </div>
        <?php endif; ?>


        <?php if (isset($this->myAccountMenu)) { ?>
            <div class="row">
                <div class="__hideMobileMenu__ col-lg-3 col-md-3 col-sm-3 col-sm-12">
                    <ul class="my-account">
                        <li role="presentation" class="<?=($this->myAccountMenu['active'] === 'myaccount' ? 'active' : '')?> panel">
                            <a href="<?=$this->url('home/myAccount')?>">Contul meu</a>
                        </li>
                        <li role="presentation" class="<?=($this->myAccountMenu['active'] === 'addad' ? 'active' : '')?> panel">
                            <a href="<?=$this->url('home/ad/create')?>">Adauga anunt</a>
                        </li>
                        <li role="presentation" class="dropdown<?=($this->myAccountMenu['active'] === 'myads' ? ' active' : '')?> panel">
                            <a aria-expanded="false" role="button" data-toggle="dropdown" class="dropdown-toggle" href="#">
                                Anunturile mele<span class="caret"></span>
                            </a>
                            <ul role="menu" class="dropdown-menu">
                                <li><a href="<?=$this->url('home/ad/myAds', ['status'=>'active'])?>">Active</a></li>
                                <li><a href="<?=$this->url('home/ad/myAds', ['status'=> 'inactive'])?>">Inactive</a></li>
                            </ul>
                        </li>

                        <li role="presentation" class="panel">
                            <a href="<?=$this->url('home/logout')?>">Logout</a>
                        </li>
                    </ul>
                </div>
                <div id ="generalContainer" class="col-lg-9 col-md-9 col-sm-9 col-sm-12">
                    <?php echo $this->content; ?>
                </div>
            </div>
        <?php } else { ?>
            <div id ="generalContainer">
                <?php echo $this->content; ?>
                <?php if (!$this->mobileApp) { ?>
                    <div class="row __hideOnMobile__" style="opacity: 0.5">
                        <div class="col-md-12" style="padding: 20px 15px 20px 15px">
                            <span class="glyphicon glyphicon-question-sign" style="color: #636e7e; font-size: 50px;"></span>
                            <h2 style="float: right; font: 300 18px 'Ubuntu',sans-serif; margin-top: 5px; padding-top: 0; width: calc(100% - 60px);">
                                Pentru orice fel de intrebari sau sugestii, nu ezitati sa ne <a href="/contact">contactati</a>.<br>
                                Sau puteti sa intrati pe blogul
                                nostru <a href="http://blog.tirbox.ro">blog.tirbox.ro</a>, pentru a fi in pas cu noile tendinte in materie de masini si
                                utilaje.
                            </h2>
                        </div>
                    </div>
                <?php } ?>
            </div>
        <?php } ?>
    </div>


    <?php if (!$this->mobileApp) { ?>
    <footer class="hidden-xs">
        <div class="newsletter">
            <p>
                <span>Aboneaza-te la newsletter</span>
                <span>Afla informatii despre oferte si partenerii nostri</span>
            </p>
            <form action="">
                <div class="form-group has-success has-feedback">
                    <input type="text" class="form-control" name="adress" placeholder="Adresa de e-mail">
                    <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
                </div>
            </form>
            <a href="#" class="button btn-green">Abonare</a>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-md-2 col-sm-4 col-xs-12 logo">
                    <a href="<?php echo $this->url('home') ?>"><img src="<?=$this->basePath() . '/img/logo-footer.png'?>" />
                    </a>
                </div>
                <div class="col-md-2 col-sm-4 col-xs-6 info hidden-xs">
                    <h3 class="">Informatii</h3>
                    <ul>
                        <li><a href="javascript:;" onclick="alert('Momentan aplicatiile mobile sunt in dezvoltare!')">Aplicatii mobile</a></li>
                        <li><a href="#">Cautari frecvente</a></li>
                        <li><a href="javascript:;" onclick="alert('Momentan anunturile nu pot fi promovate!<br />Functie in lucru!')">Anunturi promovate</a></li>
                        <li><a href="<?=$this->url('home/pages/sitemap')?>">Harta site</a></li>
                        <li><a href="<?=$this->url('home/pages/partners')?>">Parteneri </a></li>
                    </ul>
                </div>
                <div class="col-md-2 col-sm-4 col-xs-6 info2 hidden-xs">
                    <h3 class=""> &nbsp; </h3>
                    <ul>
                        <li><a href="<?=$this->url('home/contact')?>">Ajutor 24/7</a></li>
                        <li><a href="<?=$this->url('home/contact')?>">Contact</a></li>
                        <li><a href="http://blog.tirbox.ro">Blog TirBox</a></li>
                        <li><a href="<?=$this->url('home/privacy')?>">Confidentialitate</a></li>
                        <li><a href="<?=$this->url('home/terms')?>">Termeni si Conditii</a></li>
                    </ul>
                </div>
                <div class="col-md-3 col-sm-6 col-xs-12 mobile-app hidden-xs">
                    <h3>Descarca aplicatia</h3>
                    <ul>
                        <li class="ggl-play"><a href="javascript:;" onclick="alert('Momentan aplicatiile mobile sunt in dezvoltare!')"></a></li>
                        <li class="app-store"><a href="javascript:;" onclick="alert('Momentan aplicatiile mobile sunt in dezvoltare!')"></a></li>
                    </ul>
                </div>
                <div class="col-md-3 col-sm-6 col-xs-12 social-media hidden">
                    <!--<h3>Facebook</h3>-->
                    <!--<ul>
                        <li class="fb"><a href="#"></a></li>
                        <li class="tw"><a href="#"></a></li>
                        <li class="rss"><a href="#"></a></li>
                        <li class="google"><a href="#"></a></li>
                    </ul>-->
                    <div class="fb-page" data-href="https://www.facebook.com/tirbox.ro/"
                         data-tabs="timeline"
                         data-height="130"
                         data-small-header="false"
                         data-adapt-container-width="true"
                         data-hide-cover="false"
                         data-show-facepile="true"
                    ></div>

                </div>
            </div>
        </div>
    </footer>
    <?php } ?>

    <div id="scriptsGeneral">
        <?php echo $this->inlineScript()->prependScript(
            ' $(document).ready(function() { '.
                ' generalObj.onLoad(); '.
                $this->js_call.
                (isset($this->isHomePage) ? ' generalObj.sliderInit(); ' : '').
            ' ;});'
            );
        ?>
    </div>
    <?php if (isset($this->isHomePage)) { ?>
        <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
        <script src="/js/slider/ie10-viewport-bug-workaround.js"></script>

        <!-- jssor slider scripts-->
        <!-- use jssor.js + jssor.slider.js instead for development -->
        <!-- jssor.slider.mini.js = (jssor.js + jssor.slider.js) -->
        <script type="text/javascript" src="/js/slider/jssor.slider.mini.js"></script>
    <?php } ?>



    <?php // ADNOW ADV?>
    <script type="text/javascript">
        (sc_adv_out = window.sc_adv_out || []).push({
            id : "421237",
            domain : "n.ads3-adnow.com"
        });
    </script>
    <script type="text/javascript" src="//st-n.ads3-adnow.com/js/adv_out.js"></script>
    </body>
</html>