<?php echo $this->doctype();

$role = $this->authenticatedUserRole();
$user = $this->zfcUserIdentity() ? $this->zfcUserIdentity() : null;

?><html lang="ro">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <?php
    $this->headTitle()->append($this->headTitle)->setSeparator(' - ')->append('Tirbox.ro');
    echo $this->headTitle()->setAutoEscape(false)
    ?>
    <meta name="robots" content="index, follow" />
    <meta http-equiv="Content-Language" content="ro" />
    <?php echo $this->headMeta()
        ->appendName('description', $this->metaDescription)
        ->appendName('keywords', $this->metaKeywords)
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?php
    echo $this
        ->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
        ->prependStylesheet($this->basePath() . '/assets/jquery-file-upload/blueimp-gallery/blueimp-gallery.min.css')
        ->prependStylesheet($this->basePath() . '/js/nprogress-master/nprogress.css')
//            ->prependStylesheet($this->basePath() . '/css/select2/select2.min.css')
        ->prependStylesheet($this->basePath() . '/css/style.css')
        ->prependStylesheet('http://fonts.googleapis.com/css?family=Ubuntu:400,300,500,700')
        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
        ->prependStylesheet($this->basePath() . '/css/reset.css')
    ;
    ?>

    <!-- Scripts -->
    <?php echo $this->headScript()
        ->appendFile($this->basePath() . '/assets/jquery-file-upload/blueimp-gallery/jquery.blueimp-gallery.min.js', 'text/javascript')
        ->prependFile($this->basePath() . '/js/nprogress-master/nprogress.js')
        ->prependFile($this->basePath() . '/js/general.js')
        ->prependFile($this->basePath() . '/js/bootbox/bootbox.min.js')
//            ->prependFile($this->basePath() . '/js/select2/select2.full.js')
        ->prependFile($this->basePath() . '/js/bootstrap.min.js')
        ->prependFile($this->basePath() . '/js/jquery.min.js')

//            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
//            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
    ; ?>

    <script>
        <?=$this->layout()->googleAnalitics?>
    </script>
</head>
<body>
    <script>
        NProgress.set(0.5);
        NProgress.inc(0.2);
    </script>
    <?php if (APPLICATION_ENV != 'development') { ?>
    <div id="fb-root"></div>
    <script>
        (function(d, s, id) {
            var js, fjs = d.getElementsByTagName(s)[0];
            if (d.getElementById(id)) return;
            js = d.createElement(s); js.id = id;
            js.src = "//connect.facebook.net/ro_RO/sdk.js#xfbml=1&version=v2.3&appId=839888486066952";
            fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));
    </script>
    <?php } ?>
    <header>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><img src="<?=$this->basePath() . '/img/logo.jpg'?>" alt="tirbox.ro" /><?php // echo $this->translate('tirbox.ro') ?></a>
                </div>
                <div class="collapse navbar-collapse">
                    <div class="navbar-collapse collapse" id="navbar">
                        <ul class="nav navbar-nav navbar-right">
                            <li>
                                <a href="<?=$this->url('home')?>"><?php echo $this->translate('Acasa') ?></a>
                            </li>
                            <li>
                                <a href="<?=$this->url('home/offers/create')?>"><?php echo $this->translate('Cerere Oferta') ?></a>
                            </li>
                           <!--  <li>
                                <a href="#"><?php echo $this->translate('Categorii') ?></a>
                            </li> -->
                            <li>
                                <a href="<?=$this->url('home/contact')?>"><?php echo $this->translate('Contact') ?></a>
                            </li>
                            <?php if ($role == 'guest') { ?>
                                <li>
                                    <a id="loginNavMenuButton" href="javascript:;"><?php echo $this->translate('Login') ?></a>
                                </li>
                            <?php } else { ?>
                                <li><a href="<?=$this->url('home/myAccount')?>">Contul meu</a></li>
                                <li class="displayOnMobile"><a href="<?=$this->url('home/ad/create')?>">Adauga anunt</a></li>
                                <li class="displayOnMobile"><a href="<?=$this->url('home/ad/myAds', ['status'=>'active'])?>">Anunturi active</a></li>
                                <li class="displayOnMobile"><a href="<?=$this->url('home/ad/myAds', ['status'=> 'expired'])?>">Anunturi expirate</a></li>
                                <li class="displayOnMobile">
                                    <a href="<?=$this->url('zfcuser/logout')?>">Logout</a>
                                </li>
                            <?php } ?>
                            <li><a class="add-offer<?=($role == 'guest' ? ' loginActionCreateAd' : '')?>" href="<?=$this->url('home/ad/create')?>">Adauga Anunt</a></li>
                        </ul>
                    </div>
                </div><!--/.nav-collapse -->
                <?php if ($role == 'guest') { ?>
                    <div id="LoginRegisterContainer">
                        <div class="contentLoginRegister">
                            <div>
                                <img id="loginRegisterLoading" src="/img/loading.gif" style="display:none; height: 20px; padding-top: 0px">
                                <div id="errorLoginRegister"></div>
                            </div>
                            <div id="loginContainer">
                                <h4>Log in:</h4>
                                <?php echo $this->partial('scn-social-auth/user/login');?>
                            </div>
                            <div id="registerContainer">
                                <h4>Inregistreaza-te:</h4>
                                <?php echo $this->partial('scn-social-auth/user/register');?>
                            </div>
                            <div id="forgotContainer">
                                <h4>Ai uitat parola?</h4>
                                <?php echo $this->partial('scn-social-auth/user/forgot');?>
                            </div>
                        </div>
                    </div>
                <?php } ?>
            </div>
        </nav>
    </header>


        <?php // if homepage banner ?>
        <?php if (isset($this->isHomePage)) { ?>

            <!-- Jssor Slider Begin -->
            <!-- To move inline styles to css file/block, please specify a class name for each element. -->
            <!-- ================================================== -->
            <div id="generalBanner" style="display: none; position: relative; margin: 0 auto;
        top: 75px; left: 0px; width: 1200px; height: 342px; overflow: hidden; margin-bottom:75px">
                <!-- Loading Screen -->
                <div u="loading" style="position: absolute; top: 0px; left: 0px;">
                    <div style="filter: alpha(opacity=70); opacity: 0.7; position: absolute; display: block;
                top: 0px; left: 0px; width: 100%; height: 100%;">
                    </div>
                </div>
                <!-- Slides Container -->
                <div u="slides" style="cursor: move; position: absolute; left: 0px; top: 0px; width: 1200px; height: 342px; overflow: hidden;">
                    <div>
                        <img u="image" src2="<?=$this->basePath() . '/img/home-banner.jpg'?>" />
                        <div class="banner-text">
                            <span>Cauti sau vinzi piese de schimb?</span>
                            <span>Ai ajuns unde trebuie!</span>
                        </div>
                    </div>
                    <div>
                        <img u="image" src2="<?=$this->basePath() . '/img/home-banner.jpg'?>" />
                        <div class="banner-text">
                            <span>Cauti sau vinzi piese de schimb?</span>
                            <span>Ai ajuns unde trebuie!</span>
                        </div>
                    </div>
                    <div>
                        <img u="image" src2="<?=$this->basePath() . '/img/home-banner.jpg'?>" />
                        <div class="banner-text">
                            <span>Cauti sau vinzi piese de schimb?</span>
                            <span>Ai ajuns unde trebuie!</span>
                        </div>
                    </div>
                </div>

                <!--#region Bullet Navigator Skin Begin -->
                <!-- Help: http://www.jssor.com/development/slider-with-bullet-navigator-jquery.html -->
                <style>
                    /* jssor slider bullet navigator skin 21 css */
                    /*
                    .jssorb21 div           (normal)
                    .jssorb21 div:hover     (normal mouseover)
                    .jssorb21 .av           (active)
                    .jssorb21 .av:hover     (active mouseover)
                    .jssorb21 .dn           (mousedown)
                    */
                    .jssorb21 {
                        position: absolute;
                    }
                    .jssorb21 div, .jssorb21 div:hover, .jssorb21 .av {
                        position: absolute;
                        /* size of bullet elment */
                        width: 19px;
                        height: 19px;
                        text-align: center;
                        line-height: 19px;
                        color: white;
                        font-size: 12px;
                        background: url(/img/slider/b21.png) no-repeat;
                        overflow: hidden;
                        cursor: pointer;
                    }
                    .jssorb21 div { background-position: -5px -5px; }
                    .jssorb21 div:hover, .jssorb21 .av:hover { background-position: -35px -5px; }
                    .jssorb21 .av { background-position: -65px -5px; }
                    .jssorb21 .dn, .jssorb21 .dn:hover { background-position: -95px -5px; }
                </style>
                <!-- bullet navigator container -->
                <div u="navigator" class="jssorb21" style="bottom: 90px; right: 6px;">
                    <!-- bullet navigator item prototype -->
                    <div u="prototype"></div>
                </div>
                <!--#endregion Bullet Navigator Skin End -->

                <!--#region Arrow Navigator Skin Begin -->
                <!-- Help: http://www.jssor.com/development/slider-with-arrow-navigator-jquery.html -->
                <style>
                    /* jssor slider arrow navigator skin 21 css */
                    /*
                    .jssora21l                  (normal)
                    .jssora21r                  (normal)
                    .jssora21l:hover            (normal mouseover)
                    .jssora21r:hover            (normal mouseover)
                    .jssora21l.jssora21ldn      (mousedown)
                    .jssora21r.jssora21rdn      (mousedown)
                    */
                    .jssora21l, .jssora21r {
                        display: block;
                        position: absolute;
                        /* size of arrow element */
                        width: 55px;
                        height: 55px;
                        cursor: pointer;
                        background: url(/img/slider/a21.png) center center no-repeat;
                        overflow: hidden;
                    }
                    .jssora21l { background-position: -3px -33px; }
                    .jssora21r { background-position: -63px -33px; }
                    .jssora21l:hover { background-position: -123px -33px; }
                    .jssora21r:hover { background-position: -183px -33px; }
                    .jssora21l.jssora21ldn { background-position: -243px -33px; }
                    .jssora21r.jssora21rdn { background-position: -303px -33px; }
                </style>
                <!-- Arrow Left -->
            <span u="arrowleft" class="jssora21l" style="top: 123px; left: 8px;">
            </span>
                <!-- Arrow Right -->
            <span u="arrowright" class="jssora21r" style="top: 123px; right: 8px;">
            </span>
                <!--#endregion Arrow Navigator Skin End -->
                <a style="display: none" href="http://www.jssor.com">Bootstrap Slider</a>
        </div>
        <!-- Jssor Slider End -->



            <!--<div id ="generalBanner" class="banner">
                <div class="banner-img">
                    <img class="img-responsive" src="<?/*=$this->basePath() . '/img/home-banner.jpg'*/?>" />
                </div>
                <div class="banner-text">
                    <span>Cauti sau vinzi piese de schimb?</span>
                    <span>Ai ajuns unde trebuie!</span>
                </div>
            </div>-->
        <?php } elseif (isset($this->isCategoryPage)) { ?>
            <div id ="generalBanner" class="banner">
                <div class="banner-img" style="height: 180px">
                    <img class="img-responsive" src="<?=$this->basePath() . '/img/home-banner.jpg'?>" />
                </div>
            </div>
        <?php } ?>

        <div id = "mainContainer" class="container"
             <?php if (!isset($this->isHomePage) && !isset($this->isCategoryPage)) { ?>style="padding-top: 100px"<?php } ?>>

            <?php
            if (count($this->flashMessenger()->getErrorMessages())) : ?>
                <div class="alert alert-danger alert-dismissable">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                    <?php foreach ($this->flashMessenger()->getErrorMessages() as $fMessage) : ?>
                        <?php echo $fMessage . '<br />'; ?>
                    <?php endforeach; ?>
                </div>
            <?php endif; ?>

            <?php
            if (count($this->flashMessenger()->getSuccessMessages())) : ?>
                <div class="alert alert-success alert-dismissable">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                    <?php foreach ($this->flashMessenger()->getSuccessMessages() as $fMessage) : ?>
                        <?php echo $fMessage . '<br />'; ?>
                    <?php endforeach; ?>
                </div>
            <?php endif; ?>


            <?php
            if (count($this->flashMessenger()->getInfoMessages())) : ?>
                <div class="alert alert-info alert-dismissable">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                    <?php foreach ($this->flashMessenger()->getInfoMessages() as $fMessage) : ?>
                        <?php echo $fMessage . '<br />'; ?>
                    <?php endforeach; ?>
                </div>
            <?php endif; ?>

            <?php
            if (count($this->flashMessenger()->getMessages())) : ?>
                <div class="alert alert-info alert-dismissable">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                    <?php foreach ($this->flashMessenger()->getMessages() as $fMessage) : ?>
                        <?php echo $fMessage . '<br />'; ?>
                    <?php endforeach; ?>
                </div>
            <?php endif; ?>


            <?php if (isset($this->myAccountMenu)) { ?>
                <div class="row">
                    <div class="hideOnMobile col-lg-3 col-md-3 col-sm-3 col-sm-12">
                        <ul class="my-account">
                            <li role="presentation" class="<?=($this->myAccountMenu['active'] === 'myaccount' ? 'active' : '')?> panel">
                                <a href="<?=$this->url('home/myAccount')?>">Contul meu</a>
                            </li>
                            <li role="presentation" class="<?=($this->myAccountMenu['active'] === 'addad' ? 'active' : '')?> panel">
                                <a href="<?=$this->url('home/ad/create')?>">Adauga anunt</a>
                            </li>
                            <li role="presentation" class="dropdown<?=($this->myAccountMenu['active'] === 'myads' ? ' active' : '')?> panel">
                                <a aria-expanded="false" role="button" data-toggle="dropdown" class="dropdown-toggle" href="#">
                                    Anunturile mele<span class="caret"></span>
                                </a>
                                <ul role="menu" class="dropdown-menu">
                                    <li><a href="<?=$this->url('home/ad/myAds', ['status'=>'active'])?>">Active</a></li>
                                    <li><a href="<?=$this->url('home/ad/myAds', ['status'=> 'expired'])?>">Expirate</a></li>
                                </ul>
                            </li>

                            <li role="presentation" class="panel">
                                <a href="<?=$this->url('home/logout')?>">Logout</a>
                            </li>
                        </ul>
                    </div>
                    <div id ="generalContainer" class="col-lg-9 col-md-9 col-sm-9 col-sm-12">
                        <?php echo $this->content; ?>
                    </div>
                </div>
            <?php } else { ?>
                <div id ="generalContainer">
                    <?php echo $this->content; ?>
                </div>
            <?php } ?>
        </div>


        <footer>
            <div class="newsletter">
                <p>
                    <span>Aboneaza-te la newsletter</span>
                    <span>Afla informatii despre oferte si partenerii nostri</span>
                </p>
                <form action="">
                    <div class="form-group has-success has-feedback">
                        <input type="text" class="form-control" name="adress" placeholder="Adresa de e-mail">
                        <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
                    </div>
                </form>
                <a href="#" class="button btn-green">Abonare</a>
            </div>
            <div class="container">
                <div class="row">
                    <div class="col-md-2 col-sm-4 col-xs-12 logo">
                        <a href="<?php echo $this->url('home') ?>"><img src="<?=$this->basePath() . '/img/logo-footer.png'?>" />
                        </a>
                    </div>
                    <div class="col-md-2 col-sm-4 col-xs-6 info">
                        <h3>Informatii</h3>
                        <ul>
                            <li><a href="javascript:;" onclick="alert('Momentan aplicatiile mobile sunt in dezvoltare!')">Aplicatii mobile</a></li>
                            <li><a href="#">Cautari frecvente</a></li>
                            <li><a href="javascript:;" onclick="alert('Momentan anunturile nu pot fi promovate!<br />Functie in lucru!')">Anunturi promovate</a></li>
                            <li><a href="<?=$this->url('home/pages/sitemap')?>">Harta site</a></li>
                            <li><a href="<?=$this->url('home/pages/partners')?>">Parteneri </a></li>
                        </ul>
                    </div>
                    <div class="col-md-2 col-sm-4 col-xs-6 info2">
                        <h3> &nbsp; </h3>
                        <ul>
                            <li><a href="<?=$this->url('home/contact')?>">Ajutor 24/7</a></li>
                            <li><a href="<?=$this->url('home/contact')?>">Contact</a></li>
                            <li><a href="#">Descopera TirBox</a></li>
                            <li><a href="<?=$this->url('home/privacy')?>">Confidentialitate</a></li>
                            <li><a href="<?=$this->url('home/terms')?>">Termeni si Conditii</a></li>
                        </ul>
                    </div>
                    <div class="col-md-3 col-sm-6 col-xs-12 mobile-app">
                        <h3>Descarca aplicatia</h3>
                        <ul>
                            <li class="ggl-play"><a href="javascript:;" onclick="alert('Momentan aplicatiile mobile sunt in dezvoltare!')"></a></li>
                            <li class="app-store"><a href="javascript:;" onclick="alert('Momentan aplicatiile mobile sunt in dezvoltare!')"></a></li>
                        </ul>
                    </div>
                    <div class="col-md-3 col-sm-6 col-xs-12 social-media">
                        <!--<h3>Facebook</h3>-->
                        <!--<ul>
                            <li class="fb"><a href="#"></a></li>
                            <li class="tw"><a href="#"></a></li>
                            <li class="rss"><a href="#"></a></li>
                            <li class="google"><a href="#"></a></li>
                        </ul>-->
                        <div class="fb-page" data-href="https://www.facebook.com/tirbox.ro"
                             data-height="130" data-small-header="false" data-adapt-container-width="true"
                             data-hide-cover="false" data-show-facepile="false" data-show-posts="false">
                            <div class="fb-xfbml-parse-ignore">
                                <blockquote cite="https://www.facebook.com/facebook">
                                    <a href="https://www.facebook.com/www.tirbox.ro">Tirbox</a>
                                </blockquote>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </footer>

    <div id="scriptsGeneral">
        <?php echo $this->inlineScript()->prependScript(
            ' $(document).ready(function() { '.
                ' generalObj.onLoad(); '.
                $this->js_call.
            ' ;});'
            );
        ?>
    </div>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="/js/slider/ie10-viewport-bug-workaround.js"></script>

    <!-- jssor slider scripts-->
    <!-- use jssor.js + jssor.slider.js instead for development -->
    <!-- jssor.slider.mini.js = (jssor.js + jssor.slider.js) -->
    <script type="text/javascript" src="/js/slider/jssor.slider.mini.js"></script>
    <script>
        jQuery(document).ready(function ($) {

            var options = {
                $FillMode: 2,                                       //[Optional] The way to fill image in slide, 0 stretch, 1 contain (keep aspect ratio and put all inside slide), 2 cover (keep aspect ratio and cover whole slide), 4 actual size, 5 contain for large image, actual size for small image, default value is 0
                $AutoPlay: true,                                    //[Optional] Whether to auto play, to enable slideshow, this option must be set to true, default value is false
                $AutoPlayInterval: 4000,                            //[Optional] Interval (in milliseconds) to go for next slide since the previous stopped if the slider is auto playing, default value is 3000
                $PauseOnHover: 1,                                   //[Optional] Whether to pause when mouse over if a slider is auto playing, 0 no pause, 1 pause for desktop, 2 pause for touch device, 3 pause for desktop and touch device, 4 freeze for desktop, 8 freeze for touch device, 12 freeze for desktop and touch device, default value is 1

                $ArrowKeyNavigation: true,   			            //[Optional] Allows keyboard (arrow key) navigation or not, default value is false
                $SlideEasing: $JssorEasing$.$EaseOutQuint,          //[Optional] Specifies easing for right to left animation, default value is $JssorEasing$.$EaseOutQuad
                $SlideDuration: 800,                               //[Optional] Specifies default duration (swipe) for slide in milliseconds, default value is 500
                $MinDragOffsetToSlide: 20,                          //[Optional] Minimum drag offset to trigger slide , default value is 20
                //$SlideWidth: 600,                                 //[Optional] Width of every slide in pixels, default value is width of 'slides' container
                //$SlideHeight: 300,                                //[Optional] Height of every slide in pixels, default value is height of 'slides' container
                $SlideSpacing: 0, 					                //[Optional] Space between each slide in pixels, default value is 0
                $DisplayPieces: 1,                                  //[Optional] Number of pieces to display (the slideshow would be disabled if the value is set to greater than 1), the default value is 1
                $ParkingPosition: 0,                                //[Optional] The offset position to park slide (this options applys only when slideshow disabled), default value is 0.
                $UISearchMode: 1,                                   //[Optional] The way (0 parellel, 1 recursive, default value is 1) to search UI components (slides container, loading screen, navigator container, arrow navigator container, thumbnail navigator container etc).
                $PlayOrientation: 1,                                //[Optional] Orientation to play slide (for auto play, navigation), 1 horizental, 2 vertical, 5 horizental reverse, 6 vertical reverse, default value is 1
                $DragOrientation: 1,                                //[Optional] Orientation to drag slide, 0 no drag, 1 horizental, 2 vertical, 3 either, default value is 1 (Note that the $DragOrientation should be the same as $PlayOrientation when $DisplayPieces is greater than 1, or parking position is not 0)

                $BulletNavigatorOptions: {                          //[Optional] Options to specify and enable navigator or not
                    $Class: $JssorBulletNavigator$,                 //[Required] Class to create navigator instance
                    $ChanceToShow: 2,                               //[Required] 0 Never, 1 Mouse Over, 2 Always
                    $AutoCenter: 1,                                 //[Optional] Auto center navigator in parent container, 0 None, 1 Horizontal, 2 Vertical, 3 Both, default value is 0
                    $Steps: 1,                                      //[Optional] Steps to go for each navigation request, default value is 1
                    $Lanes: 1,                                      //[Optional] Specify lanes to arrange items, default value is 1
                    $SpacingX: 8,                                   //[Optional] Horizontal space between each item in pixel, default value is 0
                    $SpacingY: 8,                                   //[Optional] Vertical space between each item in pixel, default value is 0
                    $Orientation: 1,                                //[Optional] The orientation of the navigator, 1 horizontal, 2 vertical, default value is 1
                    $Scale: false                                   //Scales bullets navigator or not while slider scale
                },

                $ArrowNavigatorOptions: {                           //[Optional] Options to specify and enable arrow navigator or not
                    $Class: $JssorArrowNavigator$,                  //[Requried] Class to create arrow navigator instance
                    $ChanceToShow: 1,                               //[Required] 0 Never, 1 Mouse Over, 2 Always
                    $AutoCenter: 2,                                 //[Optional] Auto center arrows in parent container, 0 No, 1 Horizontal, 2 Vertical, 3 Both, default value is 0
                    $Steps: 1                                       //[Optional] Steps to go for each navigation request, default value is 1
                }
            };

            //Make the element 'generalBanner' visible before initialize jssor slider.
            $("#generalBanner").css("display", "block");
            var jssor_slider1 = new $JssorSlider$("generalBanner", options);

            //responsive code begin
            //you can remove responsive code if you don't want the slider scales while window resizes
            function ScaleSlider() {
                var bodyWidth = document.body.clientWidth;
                if (bodyWidth)
                    jssor_slider1.$ScaleWidth(Math.min(bodyWidth, 1920));
                else
                    window.setTimeout(ScaleSlider, 30);
            }
            ScaleSlider();

            $(window).bind("load", ScaleSlider);
            $(window).bind("resize", ScaleSlider);
            $(window).bind("orientationchange", ScaleSlider);
            //responsive code end
        });
    </script>
    </body>
</html>