<?php echo $this->doctype();

//$role = $this->AuthenticatedUserRole();
$role = \Application\libs\General::getFromSession('AuthenticatedUserRole');

$user = $this->zfcUserIdentity() ? $this->zfcUserIdentity() : null;



if ($role == 'parcauto') {
    $myPark = \Application\libs\General::getFromSession('myPark');
    $name = $myPark->getName();
} else {
    $name = $user !== null ? $user->getEmail() : '';
}

?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('tirbox.ro'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php
        echo $this
            ->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
            ->prependStylesheet($this->basePath() . '/css/select2/select2.min.css')
            ->prependStylesheet($this->basePath() . '/css/style.css')
            ->prependStylesheet('http://fonts.googleapis.com/css?family=Ubuntu:400,300,500,700')
            ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
            ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
            ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
            ->prependStylesheet($this->basePath() . '/css/reset.css')
        ;
        ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/general.js')
            ->prependFile($this->basePath() . '/js/bootbox/bootbox.min.js')
            ->prependFile($this->basePath() . '/js/select2/select2.full.js')
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')

//            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
//            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
        <header>
            <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
                <div class="container">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><img src="<?=$this->basePath() . '/img/logo.jpg'?>" alt="tirbox.ro" /><?php // echo $this->translate('tirbox.ro') ?></a>
                    </div>
                    <div class="collapse navbar-collapse">
                        <div class="navbar-collapse collapse" id="navbar">
                            <ul class="nav navbar-nav navbar-right">
                                <li>
                                    <a href="#"><?php echo $this->translate('Acasa') ?></a>
                                </li>
                                <li>
                                    <a href="#"><?php echo $this->translate('Cerere Oferta') ?></a>
                                </li>
                                <li>
                                    <a href="#"><?php echo $this->translate('Categorii') ?></a>
                                </li>
                                <li>
                                    <a href="#"><?php echo $this->translate('Contact') ?></a>
                                </li>
                                <?php if ($role == 'guest') { ?>
                                    <li>
                                        <a id="loginNavMenuButton" href="javascript:;"><?php echo $this->translate('Login') ?></a>
                                    </li>
                                <?php } else { ?>
                                    <li><a href="<?=$this->url('home/myAccount')?>">Contul Meu</a></li>
                                <?php } ?>
                                <li><a class="add-offer" href="<?=$this->url('home/ad/create')?>">Adauga Anunt</a></li>
                            </ul>
                        </div>
                    </div><!--/.nav-collapse -->
                </div>
            </nav>
        </header>

        <?php if ($role == 'guest') { ?>
        <div id="LoginRegisterContainer" style="display:none; margin-right: 20px; padding: 0px; width:100%; position: absolute;">
            <div style="background-color: #fff; border: 1px solid #eaeaea; float: right;
            margin-right: 5%; padding:0 20px 20px 20px; width: 300px;">
                <div style="min-height: 60px;">
                    <h3>Vrei sa vinzi piese?</h3>
                    <img id="loginRegisterLoading" src="/img/loading.gif" style="display:none; height: 20px; padding-top: 0px">
                    <div id="errorLoginRegister" style="color:#000; font-size: 12px; font-weight: normal"></div>
                </div>
                <div id="loginContainer">
                    <h4>Login:</h4>
                    <?php echo $this->partial('scn-social-auth/user/login');?>
                </div>
                <div id="registerContainer">
                    <h4>Inregistreaza-te:</h4>
                    <?php echo $this->partial('scn-social-auth/user/register');?>
                </div>
                <div id="forgotContainer">
                    <h4>Ai uitat parola?</h4>
                    <?php echo $this->partial('scn-social-auth/user/forgot');?>
                </div>
            </div>
        </div>
        <?php } ?>

        <?php // if homepage banner ?>
        <?php if (isset($this->isHomePage)) { ?>
            <div class="banner">
                <div class="banner-img"><img class="img-responsive" src="<?=$this->basePath() . '/img/home-banner.jpg'?>" />
                </div>
                <div class="banner-text"></div>
            </div>
        <?php } ?>


        <div class="container" style="padding-bottom: 50px">

            <?php
            if (count($this->flashMessenger()->getErrorMessages())) : ?>
                <div class="alert alert-danger alert-dismissable">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                    <?php foreach ($this->flashMessenger()->getErrorMessages() as $fMessage) : ?>
                        <?php echo $fMessage . '<br />'; ?>
                    <?php endforeach; ?>
                </div>
            <?php endif; ?>

            <?php
            if (count($this->flashMessenger()->getSuccessMessages())) : ?>
                <div class="alert alert-success alert-dismissable">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                    <?php foreach ($this->flashMessenger()->getSuccessMessages() as $fMessage) : ?>
                        <?php echo $fMessage . '<br />'; ?>
                    <?php endforeach; ?>
                </div>
            <?php endif; ?>


            <?php
            if (count($this->flashMessenger()->getInfoMessages())) : ?>
                <div class="alert alert-info alert-dismissable">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                    <?php foreach ($this->flashMessenger()->getInfoMessages() as $fMessage) : ?>
                        <?php echo $fMessage . '<br />'; ?>
                    <?php endforeach; ?>
                </div>
            <?php endif; ?>

            <?php
            if (count($this->flashMessenger()->getMessages())) : ?>
                <div class="alert alert-info alert-dismissable">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                    <?php foreach ($this->flashMessenger()->getMessages() as $fMessage) : ?>
                        <?php echo $fMessage . '<br />'; ?>
                    <?php endforeach; ?>
                </div>
            <?php endif; ?>


            <?php if (isset($this->myAccountMenu)) { ?>
                <div class="row" style="margin-top: 50px">
                    <div class="col-lg-3 col-md-3 col-sm-3 col-sm-12">
                        <h3>Meniu</h3>
                        <ul class="nav nav-pills nav-stacked">
                            <li role="presentation" class="<?=($this->myAccountMenu['active'] === 'myaccount' ? 'active' : '')?>">
                                <a href="<?=$this->url('home/myAccount')?>">Contul meu</a>
                            </li>
                            <li role="presentation" class="<?=($this->myAccountMenu['active'] === 'addad' ? 'active' : '')?>">
                                <a href="<?=$this->url('home/ad/create')?>">Adauga anunt</a>
                            </li>
                            <li role="presentation" class="dropdown<?=($this->myAccountMenu['active'] === 'myads' ? ' active' : '')?>">
                                <a aria-expanded="false" role="button" data-toggle="dropdown" class="dropdown-toggle" href="#">
                                    Anunturile mele<span class="caret"></span>
                                </a>
                                <ul role="menu" class="dropdown-menu">
                                    <li><a href="<?=$this->url('home/ad/myAds', ['status'=>'active'])?>">Active</a></li>
                                    <li><a href="<?=$this->url('home/ad/myAds', ['status'=> 'expired'])?>">Expirate</a></li>
                                </ul>
                            </li>

                            <li role="presentation">
                                <a href="<?=$this->url('zfcuser/logout')?>">Logout</a>
                            </li>
                        </ul>
                    </div>
                    <div class="col-lg-9 col-md-9 col-sm-9 col-sm-12">

                        <?php echo $this->content; ?>

                    </div>
                </div>
            <?php } else { ?>
            <?php echo $this->content; ?>
            <?php } ?>
        </div> <!-- /container -->

        <div id="footer">
            <div class="container">
                <p class="text-muted">
                    &copy; <?php echo date('Y') ?> by <a href="<?php echo $this->url('home') ?>">tirbox.ro</a>. <?php echo $this->translate('All rights reserved.') ?>
                </p>
            </div>
        </div>

        <?php echo $this->inlineScript()->prependScript(
            ' $(document).ready(function() { '.
                ' generalObj.onLoad(); '.
                $this->js_call.

            ' ;});'
        );
        ?>
    </body>
</html>
