<?php
$this->headLink()
//    ->appendStylesheet('/css/bootstrap-switch-master/bootstrap-switch.css');
;
$this->headScript()
//    ->appendFile('/js/bootstrap-switch-master/bootstrap-switch.js', 'text/javascript')
//    ->prependFile($this->basePath() . '/js/newsletter.js')
;
//$this->layout()->js_call .= ' newsletterObj.loadNewsletterOptionData("'.$this->url('kindergarten/newsletter/saveNewsletterOption').'"); ';
$role = $this->authenticatedUserRole();
?>
<h3><?=$this->translate('Contul Meu')?><?=$role === 'admin' ? ' - ADMIN TB.ro' : ''?></h3>
<div class="row">
    <div class="col-sm-12">
        <div class="panel">
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-3 col-sm-3 col-xs-12">
                        <img src="<?=$this->myAdvertiserObj->generateAvatar('160x160')?>" class="thumbnail img-responsive"/>
                    </div>
                    <div class="col-md-9 col-sm-9 col-xs-12">
                        <ul class="list-group">

                            <li class="list-group-item">
                                <span class="badge">
                                    <?=($this->myAdvertiserObj->getAccountType() === 'parc-auto' ? 'Parc Auto' : 'Particular')?>
                                </span>&nbsp;
                                <?=$this->myAdvertiserObj->getName()?>
                            </li>
                            <?php if ($this->myAdvertiserObj->getAccountType() === 'parc-auto') { ?>
                            <li class="list-group-item"><span class="badge"><?=$this->translate('nume')?></span>&nbsp;
                                <?=$this->myUser->getDisplayName()?>
                            </li>
                            <?php } ?>
                            <li class="list-group-item"><span class="badge"><?=$this->translate('Email')?></span>&nbsp;
                                <?=$this->myAdvertiserObj->getEmail()?>
                            </li>
                            <li class="list-group-item"><span class="badge"><?=$this->translate('Telefon')?></span>&nbsp;
                                <a href="tel:<?=$this->myAdvertiserObj->getTel1()?>"><?=$this->myAdvertiserObj->getTel1()?></a>
                                <a href="tel:<?=$this->myAdvertiserObj->getTel2()?>"><?=$this->myAdvertiserObj->getTel2()?></a>
                                <a href="tel:<?=$this->myAdvertiserObj->getTel3()?>"><?=$this->myAdvertiserObj->getTel3()?></a>
                            </li>
                            <li class="list-group-item"><span class="badge"><?=$this->translate('Adresa')?></span>&nbsp;
                                <?=$this->myAdvertiserObj->generateLocation()?>
                            </li>
                        </ul>
                    </div>
                </div>
                <p>
                    <?=$this->myAdvertiserObj->getDescription()?>
                </p>

                <a href="<?=$this->url('home/myAccount/update')?>" type="button" class="button btn-green"><?=$this->translate('Modifica')?></a>
                <a href="<?=$this->url('zfcuser/changepassword')?>" type="button" class="button btn-blue"><?=$this->translate('Schimba Parola')?></a>
            </div>
        </div>
    </div>
</div>

