<?php
$this->headLink()
//    ->appendStylesheet('/css/bootstrap-switch-master/bootstrap-switch.css');
;
$this->headScript()
//    ->appendFile('/js/bootstrap-switch-master/bootstrap-switch.js', 'text/javascript')
//    ->prependFile($this->basePath() . '/js/newsletter.js')
;
//$this->layout()->js_call .= ' newsletterObj.loadNewsletterOptionData("'.$this->url('kindergarten/newsletter/saveNewsletterOption').'"); ';
?>
<h3><?=$this->translate('Contul Meu')?></h3>
<div class="row">
    <div class="col-sm-12">
        <div class="panel">
            <div class="panel-body">
                <div class="row">
                    <div class="col-sm-3">
                        <img src="<?=$this->myAdvertiserObj->generateAvatar('160x160')?>" class="thumbnail img-responsive"/>
                    </div>
                    <div class="col-sm-9">
                        <ul class="list-group">

                            <li class="list-group-item">
                                <span class="badge">
                                    <?=($this->myAdvertiserObj->getAccountType() === 'parc-auto' ? 'Parc Auto' : 'Particular')?>
                                </span>&nbsp;
                                <?=$this->myAdvertiserObj->getName()?>
                            </li>
                            <li class="list-group-item"><span class="badge"><?=$this->translate('nume')?></span>&nbsp;
                                <?=$this->myUser->getDisplayName()?>
                            </li>
                            <li class="list-group-item"><span class="badge"><?=$this->translate('Email')?></span>&nbsp;
                                <?=$this->myAdvertiserObj->getEmail()?>
                            </li>
                            <li class="list-group-item"><span class="badge"><?=$this->translate('Telefon')?></span>&nbsp;
                                <?=$this->myAdvertiserObj->getTel1()?> <?=$this->myAdvertiserObj->getTel2()?> <?=$this->myAdvertiserObj->getTel3()?>
                            </li>
                            <li class="list-group-item"><span class="badge"><?=$this->translate('Adresa')?></span>&nbsp;
                                <?=$this->myAdvertiserObj->generateLocation()?>
                            </li>
                        </ul>
                    </div>

                </div>

                <p>
                    <?=$this->myAdvertiserObj->getDescription()?>
                </p>


                <a href="<?=$this->url('home/myAccount/update')?>" type="button" class="btn btn-success"><?=$this->translate('Modifica')?></a>
                <a href="<?=$this->url('zfcuser/changepassword')?>" type="button" class="btn btn-primary"><?=$this->translate('Schimba Parola')?></a>
            </div>

        </div>

    </div>
</div>

