<div class="row">
    <div class="__hideOnMobile__ col-lg-3 col-md-3 col-sm-3 col-sm-12">
        <ul class="my-account">
            <li role="presentation" class="active panel">
                <a href="#">Cerere Oferta</a>
            </li>
        </ul>
        <p>Trimite-ne mesajul tau si iti vom raspunde in maxim 24 ore!</p>

        <p>
            Puteti sa ne contactati pentru o oferta de piese direct prin departamentul de vanzari: <br />
            &bull; e-mail: <a href="mailto:vanzari@tirbox.ro?subject=Cerere Oferta&body=">vanzari@tirbox.ro</a><br />
        </p>
    </div>
    <div class="col-lg-9 col-md-9 col-sm-9 col-sm-12">
        <h3><?=$this->translate('Cerere Oferta Personalizata pentru nevoile tale')?></h3>
        <div class="panel card card-1">
            <div class="panel-body">
                <?php
                \Application\View\Helper\Forms::render(
                    $this,
                    $this->form,
                    $this->url('home/offers/create'),
                    [
                        'label_size' => 'col-lg-2 col-md-2 col-sm-2 col-xs-12',
                        'input_size' => 'col-lg-10 col-md-10 col-sm-10 col-xs-12',

                    ]
                );
                ?>
            </div>
        </div>
    </div>
</div>
