<div class="row">
    <div class="hideOnMobile col-lg-3 col-md-3 col-sm-3 col-sm-12">
        <ul class="my-account">
            <li role="presentation" class="active panel">
                <a href="#">Cerere Oferta</a>
            </li>
        </ul>
        <p>Trimite-ne mesajul tau si iti vom raspunde in maxim 24 ore!</p>

        <p>
            Puteti sa ne contactati pentru o oferta de piese direct prin departamentul de vanzari: <br />
            &bull; e-mail: <a href="mailto:vanzari@tirbox.ro">vanzari@tirbox.ro</a><br />
            &bull; telefon: <a href="tel:0734.123.654">0734.123.654</a><br />
        </p>
    </div>
    <div class="col-lg-9 col-md-9 col-sm-9 col-sm-12">
        <h3><?=$this->translate('Cerere Oferta Personalizata pentru nevoile tale')?></h3>
        <?php
        \Application\View\Helper\Forms::render(
            $this,
            $this->form,
            $this->url('home/offers/create'),
            [
                'label_size' => 'col-lg-2 col-md-2 col-sm-2 col-xs-12',
                'input_size' => 'col-lg-10 col-md-10 col-sm-10 col-xs-12',

            ]
        );
        ?>
    </div>
</div>
