
<div class="row">
    <div class="col-md-3">
        <h2>Cerere Oferta</h2>

        Puteti sa ne contactati pentru o oferta de piese direct prin departamentul de vanzari: <br />
        &bull; e-mail: <a href="mailto:vanzari@tirbox.ro">vanzari@tirbox.ro</a><br />
        &bull; telefon: <a href="tel:0734.123.654">0734.123.654</a><br />

    </div>
    <div class="col-md-9">
        <?php
        \Application\View\Helper\Forms::render(
            $this,
            $this->form,
            $this->url('home/contact'),
            [
                'label_size' => 'col-lg-2 col-md-2 col-sm-2 col-xs-12',
                'input_size' => 'col-lg-10 col-md-10 col-sm-10 col-xs-12',

            ]
        );
        ?>
    </div>
</div>