<div class="row">
    <div class="hideOnMobile col-lg-3 col-md-3 col-sm-3 col-sm-12">
        <ul class="my-account">
            <li role="presentation" class="active panel">
                <a href="#">Contact</a>
            </li>
        </ul>
        Departament Vanzari: <br />
        &bull; e-mail: <a href="mailto:vanzari@tirbox.ro">vanzari@tirbox.ro</a><br />
        &bull; telefon: <a href="tel:0740258207">0740.258.207</a><br />
        <br />
        Departament Tehnic: <br />
        &bull; e-mail: <a href="mailto:contact@tirbox.ro">contact@tirbox.ro</a><br />
        &bull; telefon: <a href="tel:0740258207">0740.258.207</a><br />
    </div>
    <div class="col-lg-9 col-md-9 col-sm-9 col-sm-12">
        <h3><?=$this->translate('Contacteaza-ne pentru orice problema pe care o intampini')?></h3>
        <?php
        \Application\View\Helper\Forms::render(
            $this,
            $this->form,
            $this->url('home/contact'),
            [
                'label_size' => 'col-lg-2 col-md-2 col-sm-2 col-xs-12',
                'input_size' => 'col-lg-10 col-md-10 col-sm-10 col-xs-12',

            ]
        );
        ?>
    </div>
</div>