
<div class="row">
    <div class="col-md-3">
        <h2>Contact</h2>

        formular de contact
    </div>
    <div class="col-md-9">
        <?php
        \Application\View\Helper\Forms::render(
            $this,
            $this->form,
            $this->url('home/contact'),
            [
                'label_size' => 'col-lg-2 col-md-2 col-sm-2 col-xs-12',
                'input_size' => 'col-lg-10 col-md-10 col-sm-10 col-xs-12',

            ]
        );
        ?>
    </div>
</div>