
<div class="row">
    <div class="col-md-3">
        <h2>Parteneri TirBox</h2>
        Devino si tu partener tirbox.ro si beneficiezi de o oferta avantajoasa pentru parcul tau auto. Deasemenea, vei
        obtine un trafic sporit pe site-ul personal.<br /><br />

        Departament Vanzari: <br />
        &bull; e-mail: <a href="mailto:vanzari@tirbox.ro:?subject=Cerere Parteneriat Tirbox.ro">vanzari@tirbox.ro</a><br />
        &bull; telefon: <a href="tel:0740258207">0740.258.207</a><br />

    </div>
    <div class="col-md-9">

        <div class="right-pic panel" style="float: left;">
            <div class="col-md-4 col-sm-4 col-xs-12">
                <img class="img-responsive" src="<?=$this->basePath() . '/img/comercials-right.jpg'?>"/>
            </div>
            <div class="col-md-8 col-sm-8 col-xs-12 partnerInfo" style="padding-left: 20px;">
                <h4>Volvo Dezmembrari</h4>
                <p>
                    Piese auto noi si second-hand pentru toate autoturismele din gama Volvo.
                </p>
                    <strong>Contact</strong><br />
                tel: <a href="tel:0767.448.668">0767.448.668</a><br />
                e-mail: volvo_dez@yahoo.com<br />
                <a href="http://www.volvodez.ro">http://www.volvodez.ro</a>
            </div>
        </div>

        <div class="right-pic panel" style="float: left;">
            <div class="col-md-4 col-sm-4 col-xs-12">
                <img class="img-responsive" style="margin: auto; padding-top: 40px" src="<?=$this->basePath() . '/img/logo-footer.png'?>"/>
            </div>
            <div class="col-md-8 col-sm-8 col-xs-12 partnerInfo" style="padding-left: 20px;">
                <h4>Devino si tu partener Tirbox.ro</h4>
                <p>
                    Beneficiezi de o oferta avantajoasa pentru parcul tau auto. Deasemenea, vei
                    obtine un trafic sporit pe site-ul personal.
                </p>
                <strong>Contact</strong><br />
                tel: <a href="tel:0740258207">0740.258.207</a><br />
                e-mail: <a href="mailto:vanzari@tirbox.ro:?subject=Cerere Parteneriat Tirbox.ro">vanzari@tirbox.ro</a><br />
            </div>
        </div>

    </div>
</div>