<h2>Confidentialitate</h2>

<section class="rules" id="body-container">
    <div class="wrapper">
        <div class="content text">
            <h3>Reguli</h3>
            <div class="bgef pding5_10">
                <h5>
                    1. Politica de confidentialitate si folositea cookie-urilor
                    <a href="#top"><span class="glyphicon glyphicon-arrow-up"></span></a>
                </h5>
            </div>
            <ul class="separate">
                <li>&bull; Tirbox.ro recunoaşte şi respectă dreptul persoanelor la confidenţialitatea datelor cu caracter personal.</li>
                <li>&bull; Vă informăm că datele de contact pe care decideşi să ni le funizaţi sunt „date cu caracter personal” conform prevederilor Legii nr. 677/2001 din România.</li>
                <li>&bull; Politica de confidenţialitate a tirbox.ro se aplică colectării, folosirii, dezvăluirii şi protejării informaţiilor personale pe care decideţi să le furnizaţi.</li>
                <li>&bull; Vă rugăm să citiţi următoarele, pentru a afla mai multe despre politica de confidenţialitate şi practicile noastre privind datele personale.</li>
            </ul>

            <br />
            <div class="bgef pding5_10">
                <h5>
                    2. De ce colectăm date cu caracter personal?
                    <a href="#top"><span class="glyphicon glyphicon-arrow-up"></span></a>
                </h5>
            </div>
            Colectăm date cu caracter personal în urmatoarele scopuri:
            <ul>
                <li>&bull; pentru a ne asigura că pagina de web este relevantă pentru nevoile dumneavoastră;</li>
                <li>&bull; pentru a vă confirma serviciile pe care le-aţi achiziţionat în sistem on-line şi a vă furniza informaţii suplimentare cu privire la aceste servicii;</li>
                <li>&bull; transmiterii de oferte, mesaje publicitare şi de marketing;</li>
                <li>&bull; informaţii despre promoţii prin poşta şi telefon, SMS, sau alte mijloace de comunicare cu privire la serviciile tirbox.ro sau ale firmelor partenere;</li>
                <li>&bull; în vederea îndeplinirii obligaţiilor legale şi responsabilităţilor sociale conform normelor românesti şi  internaţionale;</li>
            </ul>
            Tirbox.ro poate dezvălui datele cu caracter personal către terţi dacă acest lucru este cerut de lege sau în cazurile de bună-credinţă în care aceste acţiuni sunt necesare pentru conformarea la dispoziţiile legale; protejarea şi apărarea drepturilor de proprietate ale tirbox.ro; acţionarea în circumstanţe de urgenţă pentru protejarea siguranţei personale a angajaţilor, utilizatorilor de produse sau servicii.<br /><br />
            Atunci când tirbox.ro este solicitat să furnizeze date cu caracter personal sau nu se permite acest lucru, vor fi dezvăluite doar acele date necesare îndeplinirii stricte a obiectului solicitării.<br />

            <br />
            <div class="bgef pding5_10">
                <h5>
                    3. Cum putem folosi aceste informaţii?
                    <a href="#top"><span class="glyphicon glyphicon-arrow-up"></span></a>
                </h5>
            </div>
            Aceste date sunt folosite, conform celor indicate mai sus, în diferite scopuri. Câteva exemple specifice includ:
            <ul>
                <li>&bull; procesarea cererii dvs. de înregistrare, de solicitare de informaţii sau reclamaţiile dvs;</li>
                <li>&bull; furnizarea de informaţii cu privire la activităţile în desfăşurare ale tirbox.ro;</li>
                <li>&bull; posibilitatea invitării dvs. la campaanii, activităţi viitoare organizate de toirbox.ro sau partenerii acestuia.</li>
                <li>&bull; facturării serviciilor comandate de dumneavoastră;</li>
                <li>&bull; efectuării plaţii on-line;</li>
                <li>&bull; asigurării securităţii tranzacţiei / plăţii on-line / carte de credit prin aplicarea de filtre antifraude</li>
                <li>&bull; realizării de rapoarte / analize;</li>
                <li>&bull; publicării, promovării, ofertarii serviciilor oferite de tirbox.ro</li>
            </ul>

            <br />
            <div class="bgef pding5_10">
                <h5>
                    4. Ce informaţii colectăm?
                    <a href="#top"><span class="glyphicon glyphicon-arrow-up"></span></a>
                </h5>
            </div>
            În vederea îndeplinirii scopurilor menţionate mai sus, cu diverse ocazii, tirbox.ro vă poate solicita date care să ne permită să va contactăm, cum ar fi: numele dvs., adresa de email, numărul de telefon, adresa poştală, etc.<br /><br />
            Acest lucru se poate întâmpla când vizitaţi site-ul nostru, cu ocazia discuţiilor personale cu angajaţii noştri, cu ocazia participării la un chestionar sau la orice altă activitate de participare publică. Anumite informaţii despre computerele celor care accesează website-ul sunt colectate automat (vezi mai jos).<br /><br />
            „Cookies” – aşa cum este o practică obişnuită pentru site-urile multor societăţi, şi site-ul TIRBOX.RO foloseşte „cookies” şi alte tehnologii pentru a ne ajuta să înţelegem care părţi ale site-ului sunt cele mai populare, ce anume accesează vizitatorii noştri pe site şi cât timp petrec acolo. Folosim tehnologii cum ar fi „cookies” pentru a studia eficacitatea comunicaţiilor cu vizitatorii noştri, în vederea îmbunătăţirii constante a site-ului/site-urilor noastre.<br /><br />
            Informaţii de tip „Log” - serverele noastre înregistrează automat informaţiile pe care le trimite serverul dvs. atunci când vizitaţi site-ul nostru. Aceste înregistrări pot include informaţii referitoare la căutarea (electronică) pe web, adresa IP, tipul de „browser”, limbajul „browserului”, data şi ora căutarii dvs. şi una sau mai multe „cookies” care pot identifica în mod unic „browserul” dvs.<br /><br />
            Informaţii privind „user”-ul– când trimiteţi un email sau folosiţi alt tip de comunicare cu TIRBOX.RO, putem stoca aceste informaţii pentru a putea procesa cererile dvs., a le răspunde şi pentru a ne îmbunătăţi serviciile şi activităţile.<br /><br />

            <br />
            <div class="bgef pding5_10">
                <h5>
                    5. Utilizarea cookie-urilor
                    <a href="#top"><span class="glyphicon glyphicon-arrow-up"></span></a>
                </h5>
            </div>
            Cookie-urile (terminologia include "Internet Cookie", "browser cookie", "HTTP cookie" sau pur și simplu "cookie" ) sunt fişiere sau informaţii care pot fi stocate pe calculatorul dumneavoastră sau pe dispozitive mobile, cu acces la Internet (smartphone sau tableta) atunci când accesaţi Internetul. Cookie-ul este instalat prin solicitarea emisă de către un web-server unui browser (ex: Internet Explorer, Chrome) şi nu poate accesa informaţiile de pe calculatorul/dispozitivul mobil al utilizatorului. Menţionăm că această tehnologie nu conţine programe software, viruşi sau spyware.<br /><br />
            Utilizăm cookie-urile pentru a face Site-ul mai uşor de utilizat şi pentru a-l adapta mai bine, prin ofertele noastre, la interesele şi necesităţile dumneavoastră. Cookie-urile sunt utilizate şi pentru a mări viteza viitoarelor dumneavoastră activităţi şi experienţe pe site-ul nostru. Acestea se referă la preferinţele dvs. în materie de confidenţialitate online sau publicitate relevantă. De asemenea utilizăm cookie-uri pentru a compila statistici anonime, cumulate, care ne permit să înţelegem cum utilizează oamenii Site-ul şi pentru a ne ajuta să îmbunătăţim structura şi conţinutul lui, excluzând indentificarea personală a utilizatorului.<br /><br />


            <br />
            <div class="bgef pding5_10">
                <h5>
                    6. Cum pot să controlez sau să şterg cookie-urile?
                    <a href="#top"><span class="glyphicon glyphicon-arrow-up"></span></a>
                </h5>
            </div>
            Majoritatea browserelor de Internet sunt setate iniţial pentru a accepta automat cookie-uri. Puteţi modifica setările pentru a bloca cookie-urile sau pentru fi notificat în momentul când sunt trimise cookie-uri către calculatorul sau dispozitivul dumneavoastră mobil (smartphone, tabletă).<br /><br />
            În cazul în care anulaţi cookie-urile pe care le utilizăm, nu veţi mai primi informaţii personalizate atunci când vizitaţi site-ul tirbox.ro.<br /><br />
            Dacă utilizaţi mai multe dispozitive pentru a vizualiza şi a accesa Site-ul (de ex. calculatorul, smartphone, tableta, etc) va trebui să vă asiguraţi că fiecare browser de pe fiecare dispozitiv este setat astfel încât să corespundă preferinţelor dumneavoastră de cookie.<br /><br />
            Mai jos aveţi câteva link-uri, care vă explică cum puteţi schimba setările cookie-urilor. Aceste setări se găsesc de regulă în "opţiuni" sau în meniul de "preferinţe" al browserului. Pentru mai multe detalii puteţi folosi şi opţiunea "ajutor" a browserului dumneavoastră.<br /><br />
            Cookie settings în Internet Explorer<br />
            Cookie settings în Firefox<br />
            Cookie settings în Chrome<br />
            Cookie settings în Safari<br /><br />

            <br />
            <div class="bgef pding5_10">
                <h5>
                    7. Securitatea informaţiilor
                    <a href="#top"><span class="glyphicon glyphicon-arrow-up"></span></a>
                </h5>
            </div>
            Tratăm securitatea informaţiilor dvs. în mod foarte serios, de aceea, luăm importante măsuri de securitate, necesare pentru protecţia împotriva accesului neautorizat la date sau modificării, dezvăluirii sau distrugerii neautorizate de date. Acest lucru presupune revizuiri interne ale practicilor de colectare, păstrare şi procesare de date şi ale măsurilor de securitate, de asemenea, măsuri fizice de securitate pentru protecţia împotriva accesului neautorizat la sistemele unde stocăm datele personale.<br /><br />
            Accesul la datele personale este permis numai angajaţilor autorizaţi ai TIRBOX.RO sau ai entităţilor din acelaşi grup ca şi TIRBOX.RO, cărora le sunt necesare aceste date în vederea operării, dezvoltării şi îmbunătăţirii serviciilor noastre. Aceste persoane sunt obligate să păstreze confidenţialitatea acestor date, fiind instruite cu privire la protecţia datelor cu caracter personal.<br /><br />


            <br />
            <div class="bgef pding5_10">
                <h5>
                    8. Integritatea datelor
                    <a href="#top"><span class="glyphicon glyphicon-arrow-up"></span></a>
                </h5>
            </div>
            Tirbox.ro procesează date personale doar în scopul pentru care au fost colectate şi conform acestei Politici. Revizuim practicile noastre de colectare, stocare şi procesare de date pentru a ne asigura că procesam, colectăm şi stocăm numai acele date necesare pentru furnizarea sau îmbunătăţirea serviciilor şi activităţilor noastre. Luăm măsurile necesare în măsura posibilităţilor, pentru a ne asigura că datele personale pe care le procesăm sunt corecte, complete şi actuale, dar depindem de utilizatorii noştri pentru a ne furniza date actualizate sau pentru a corecta datele lor personale acolo unde este necesar.<br /><br />
            Prin completarea datelor, dumneavoastra va exprimti acordul expres si neechivoc ca orice date cu caracter personal, precum si orice alte informatii furnizate de dumneavoastra, să fie procesate si folosite de tirbox.ro.<br /><br />
            Datele cu caracter personal nu vor fi dezvăluite către terti cu exceptia împuternicitilor TIRBOX.RO pentru prelucrarea de date personale si cu exceptia cazurilor în care TIRBOX.RO trebuie să respecte obligatiile impuse de legislatia în vigoare.<br /><br />
            Conform Legii nr. 677/ 2001 pentru protecţia persoanelor cu privire la prelucrarea datelor cu caracter personal şi liberă circulaţie a acestor date, beneficiati de urmatoarele drepturi:
            <ul>
                <li>&bull; Dreptul la informare : dreptul de a fi informat cu privire la identitatea operatorului de date personale, scopul în care se face prelucrarea datelor, destinatarii sau categoriile de destinatari ai datelor, existenţa drepturilor prevăzute de Legea nr. 677/ 2001 pentru persoana vizată şi condiţiile în care pot fi exercitate;</li>
                <li>&bull; Dreptul de acces la date: dreptul de a obţine de la operator la cerere şi în mod gratuit, pentru o solicitare pe an, confirmarea faptului că datele în legatură cu dumneavoastra sunt sau nu prelucrate de către acesta.</li>
                <li>&bull; Dreptul de intervenţie: dreptul de a obţine, la cerere şi în mod gratuit, rectificarea, actualizarea, blocarea, ştergerea sau transformarea în date anonime a datelor a căror prelucrare nu este conformă legii, în special a datelor incomplete sau inexacte;</li
            </ul>
            Pentru exercitarea oricaruia dintre aceste drepturi, utilizatorul se poate adresa cu o cerere scrisa in acest sens pe mail la contact @ tirbox .ro.



        </div>
    </div>
</section>