<h2>Termeni si Conditii</h2>

<section class="rules" id="body-container">
    <div class="wrapper">
        <div class="content text">
            Va rugam sa cititi cu atentie prezentele „Termeni si conditii” respectiv „Politica de confidentialitate si utilizare a cookies”. Daca nu sunteti de acord cu ele in totalitate, va rugam sa nu folositi site-ul tirbox.ro.<br /><br />
            Pentru a folosi site-ul tirbox.ro trebuie sa aveti minim 18 ani.<br /><br />

            <h5>1. Definitii<a href="#top"><span class="glyphicon glyphicon-arrow-up"></span></a></h5>
            tirbox.ro / site-ul tirbox.ro – este pagina de internet www.tirbox.ro, impreuna cu toate sectiunile (subpaginile acesteia). Se exclud: paginile de internet apartinand unor terti, vizitate ca urmare  accesarii informatiilor sau link-uri prezentate pe tirbox.ro;<br /><br />
            utilizatori– orice persoana fizica care viziteaza site-ul tirbox.ro, precum orice PFA sau persoana juridica care foloseste/ achizitioneaza serviciile oferite de tirbox.ro;<br /><br />
            anunt – o oferta de bunuri sau servicii pe care utilizatorul o lanseaza pentru a fi publicata de catre tirbox.ro;<br /><br />
            produs/obiect al anuntului -  bun sau serviciu disponibil pentru a fi comercializat de catre utilizator, respectand legislatia in vigoare.<br /><br />

            <h5>2. Prevederi generale<a href="#top"><span class="glyphicon glyphicon-arrow-up"></span></a></h5>
            Site-ul tirbox.ro nu vinde nici un fel de produse, fiind un site care ofera posibilitatea de a publica anunturi. Nu suntem furnizori de piese auto, magazin online sau parc de dezmembrari. Responsabilitatea asupra continutului anunturilor revine in intregime utilizatorilor.<br /><br />
            Tirbox.ro nu este responsabil de informatiile oferite de utilizatori pe acest site, vericiditatea lor, greselile de scriere.<br /><br />

            <h5>3. Conditii pentru  adaugarea de anunturi pe site-ul tirbox.ro:<a href="#top"><span class="glyphicon glyphicon-arrow-up"></span></a></h5>
            <ul>
                <li>&bull; Dorim sa gazduim un continut de calitate si real pe site-ul nostru  si pentru aceea tirbox.ro isi rezerva dreptul de a sterge/modifica orice anunt care nu respecta „Termeni si conditii”, fara notificare prealabila;</li>
                <li>&bull; Responsabilitatea asupra continutului anunturilor, imaginilor incarcate, obiectelor/ serviciilor promovate prin anunturi revine in intregime utilizatorilor;</li>
                <li>&bull; Este strict interzisa postarea de anunturi pentru vanzarea sau promovare de obiecte considerate de legislatia in vigoare ca fiind: ilegale, interzise, contrafacute, replici, periculoase (de ex. bunuri dobandite ilicit);</li>
                <li>&bull; Nu folositi doar majuscule, caractere speciale la completarea anunturilor;</li>
                <li>&bull; Link-urile catre site-uri terte, promovarea altor site-uri, reclama sau publicitatea (atat in textul anuntului cat si in imaginile incarcate pe site)  este interzisa fara acordul tirbox.ro;</li>
                <li>&bull; Nu adaugati in corpul mesajului mailul de contact sau numarul de telefon, acestea se completeaza in campurile destinate o data cu crearea contului;</li>
                <li>&bull; Anunturile trebuie incadrate corect: categorie/marca/model. Anunturile generale nu sunt acceptate;</li>
                <li>&bull; Un anunt este valabil pentru un singur produs/reper;</li>
                <li>&bull; Nu sunt acceptate anunturi cu oferte fictive care nu promoveaza ceva concret sau real (de ex. Vand orice piesa tractor...)</li>
                <li>&bull; Preturile din anunturi trebuie sa fie reale. Anunturile cu preturi pe care tirbox.ro le considera nereale, vor fi sterse;</li>
                <li>&bull; Tirbox.ro poate oferi servicii de anunturi promovate, conform si in conditiile ofertei prezentate pe site.</li>
            </ul>

            <h5>4. Drepturile si obligatiile utilizatorilor site-ului tirbox.ro:<a href="#top"><span class="glyphicon glyphicon-arrow-up"></span></a></h5>
            <ul>
                <li>&bull; Utilizatorul are dreptul de beneficia de toate serviciile oferite de site-ul tirbox.ro. Utilizarea site-ului tirbox.ro se este gratuita cu exceptia serviciilor oferite contra cost, optionale, conform ofertei  in vigoare, prezentata pe site;</li>
                <li>&bull; Utilizatorul isi asuma in intregime raspunderea pentru continutul anunturilor  si declara pe proprie raspundere ca este proprietarul de drept al produselor/serviciilor promovate prin anunturile sale pe pagina tirbox.ro. Deasemenea utilizatorul declara pe proprie raspundere ca este titularul tuturor drepturilor de proprietatea intelectuala, inclusiv al drepturilor de autor in privinta continutului publicat, inclusiv fotografii;</li>
                <li>&bull; Numele de utilizator (e-mail), contul de utilizator si parola aferenta au caracter individual si netransmisibil. Utilizatorul este pe deplin responsabil pentru utilizarea contului. In acest sens va obligati sa utilizati personal contul dumneavoastra, sa nu transferati, cesionati, vindeti, imprumuta sau transmite in orice alt mod contul dvs. de utilizator si/sau parola aferenta unei terte persoane sau entitati. Daca aveti suspiciuni privind orice utilizare neautorizata a contului dvs. sau accesare neautorizata a parolei dumneavoastra va rog sa ne anuntati printr-un email la contact @ tirbox .ro . Tirbox.ro isi rezerva dreptul de a suspenda/sterge orice cont;</li>
                <li>&bull; Utilizatorul este de acord sa exonereze de raspundere si sa nu actioneze tirbox.ro in justitie, cu privire la orice pretentie ridicata de catre un tert rezultata din utilizarea serviciilor tirbox.ro de catre terti, cat si cu privire la orice pierdere (directa, indirecta, pe cale de consecinta sau de alta natura), costuri, actiuni, procese, pretentii, stricaciuni, cheltuieli (inclusiv cheltuieli de judecata) sau alte raspunderi, suferite in vreun fel, sau provocate direct, ca urmare a incalcarii sau ignorarii de catre utilizator a acestor termeni si conditii;</li>
                <li>&bull; Utilizatorul nu va posta in mod rauvoitor (intentionat) anunturi cu caracter calomnios sau injurios, de farsa, pentru a cauza neplaceri, sau a aduce atingere imaginii altor clienti/utilizatori ai acestor servicii. Utilizatorii care nu respecta aceste conditii pot fi urmariti si actionati in instanta, civil si penal, pe baza IP-urilor si/sau datelor de identificare introduse la postarea anunturilor.</li>
            </ul>

            <h5>5. Drepturile si obligatiile site-ului tirbox.ro:<a href="#top"><span class="glyphicon glyphicon-arrow-up"></span></a></h5>
            <ul>
                <li>&bull; Tirbox.ro va publica anunturile utilizatorilor care vor respecta prevederile „Termeni si conditii”. Deasemenea vom incerca sa remediem cat mai repede posibil eventualele disfunctionalitati sau sesizari venite  de la  utilizatori;</li>
                <li>&bull; Nu garantam ca serviciul va fi disponibil neintrerupt sau fara erori. Tirbox.ro nu va fi responsabil pentru orice pierderi de natura directa sau indirecta rezultate ca urmare a disponibilitatii sau folosirii serviciilor noastre;</li>
                <li>&bull; Tirbox.ro nu isi asuma raspunderea si nu poate fi facut responsabil de activitatile utilizatorilor, de continutul anunturilor, vericiditatea lor, calitatea, cantitatea sau disponibilitate obiecteler sau serviciilor care fac obiectul anunturilor.</li>
                <li>&bull; In cazul in care utilizatorul publica anunturi care nu respecta „Termeni si conditii”, tirbox.ro isi rezerva dreptul de a sterge anunturile, fara notificare si/sau de a bloca accesul utilizatorului la site-ul tirbox.ro in vederea postarii de noi anunturi sau administrarii anunturilor existente.</li>
            </ul>

            Ne rezervam dreptul de a modifica prezentele : „Termeni si conditii” fara a notifica in prealabil persoanele care utilizeaza acest site.<br /><br />
            Utilizatorul are dreptul de a verifica periodic continutul „Termeni si conditii”.

        </div>
    </div>
</section>