

<div class="announcement row panel">
    <div class="picture col-md-2 col-sm-2 col-xs-12">
        <a href="<?=$this->href?>" title="<?=$this->car?> <?=$this->model?> - <?=$this->title?>">
            <img class="media-object" src="<?=$this->imgSrc?>" data-holder-rendered="true">
        </a>
    </div>
    <div class="description col-md-8 col-sm-8 col-xs-12">
        <h4 class="media-heading">
            <a title="<?=$this->car?> <?=$this->model?> - <?=$this->title?>" href="<?=$this->href?>"><?=$this->title?></a>
            <span class="stare"><?=($this->stare == 'nou' ? $this->translate('Nou') : $this->translate('Second'))?></span>
        </h4>
        <div>
            <span><span class="glyphicon glyphicon-eye-open"></span> Vizualizari: <?=$this->views?></span>
            <span><span class="glyphicon glyphicon-earphone"></span> Contact Afisat: <?=$this->contactDisplayed?></span>
        </div>
        <p class="about"><?=$this->description?></p>
        <p class="model">
            <span class="category-icon">
                <img src="<?=$this->basePath()?>/img/categ_<?=$this->carCategory?>.png?v=<?=TBVER?>" />
            </span>
            <a href="<?=$this->urlFilter1?>" title="Piese <?=$this->car?>">
                <?=$this->car?>
            </a>
            <?php
            $x = explode(',', $this->model);
            foreach ($x as $model) {
                $model = trim($model);
                ?>
                <a href="<?=str_replace('__search__', $model, $this->urlFilter2)?>" title="Piese <?=$this->car?> <?=$model?>">
                    <?=$model?></a>,
                <?php
            }
            ?>

            (<?=$this->yearStart?> - <?=$this->yearEnd?>)
        </p>
        <?php if ($this->status == 'inactive') { ?>
        <a href="<?=$this->url('home/ad/changeStatus', ['mode'=>'activate', 'id'=>$this->id, 'token'=>$this->token])?>"
           class="btn-green button" role="button">Reactiveaza Anunt</a>
        <?php } else { ?>
        <a href="<?=$this->url('home/ad/create', ['id'=>$this->id])?>" class="btn-green button" role="button">Modifica Anunt</a>

        <a href="javascript:;" onclick="<?=\Application\libs\General::confirmBoxJS(
            $this,
            $this->url('home/ad/changeStatus', ['mode'=>'disable', 'id'=>$this->id, 'token'=>$this->token]),
            'Vrei sa stergi definitiv acest anunt?'
        )?>"
           class="btn-red button" role="button">Dezactiveaza Anunt</a>
        <?php } ?>
    </div>
    <div class="col-md-2 col-sm-2 col-xs-12">
        <span class="price"><?=$this->price?></span>
        <span class="county"><?=$this->county?></span>
    </div>
</div>