<div class="announcement row panel">
    <div class="picture col-md-2 col-sm-2 col-xs-12">
        <a href="<?=$this->href?>">
            <img class="media-object" src="<?=$this->imgSrc?>" data-holder-rendered="true">
        </a>
    </div>
    <div class="description col-md-8 col-sm-8 col-xs-12">
        <h4 class="media-heading"><a href="<?=$this->href?>"><?=$this->title?></a></h4>
        <p class="about"><?=$this->description?></p>
        <p class="model"><?=$this->car?> <?=$this->model?> (<?=$this->yearStart?> - <?=$this->yearEnd?>)</p>
    </div>
    <div class="price col-md-2 col-sm-2 col-xs-12"><span>500 euor<?=$this->state_id?></span></div>
</div>