<div class="media">
    <div class="media-left">
        <a href="<?=($this->status == 'ok' ? $this->href : '#')?>">
            <img class="media-object" src="<?=$this->imgSrc?>" data-holder-rendered="true">
        </a>
    </div>
    <div class="media-body">
        <h4 class="media-heading">
            <?php if ($this->status == 'ok') { ?>
            <a href="<?=$this->href?>"><?=$this->title?></a>
            <?php } else { ?>
                <?=$this->title?>
            <?php } ?>
        </h4>
        <p><?=$this->description?></p>
        <p><?=$this->car?></p>
        <?php if ($this->status == 'expired') { ?>
        <a href="<?=$this->url('home/ad/changeStatus', ['mode'=>'activate', 'id'=>$this->id, 'token'=>$this->token])?>"
           class="btn btn-primary btn-sm" role="button">Reactiveaza Anunt</a>
        <?php } else { ?>
        <a href="<?=$this->url('home/ad/create', ['id'=>$this->id])?>" class="btn btn-success btn-sm" role="button">Modifica Anunt</a>
        <?php } ?>
        <a href="javascript:;" onclick="<?=\Application\libs\General::confirmBoxJS(
            $this,
            $this->url('home/ad/changeStatus', ['mode'=>'delete', 'id'=>$this->id, 'token'=>$this->token]),
            'Vrei sa stergi definitiv acest anunt?'
        )?>"
           class="btn btn-danger btn-sm" role="button">Sterge Anunt</a>
    </div>
</div>