
<div class="media" style="border-bottom: 1px solid #DADADA; padding:10px 0 20px 0">
    <div class="media-left">
        <a href="<?=($this->status == 'ok' ? $this->href : '#')?>">
            <img class="media-object" src="<?=$this->imgSrc?>" data-holder-rendered="true">
        </a>
    </div>
    <div class="media-body">
        <h4 class="media-heading">
            <?php if ($this->status == 'ok') { ?>
            <a href="<?=$this->href?>"><?=$this->title?></a>
            <?php } else { ?>
                <?=$this->title?>
            <?php } ?>
        </h4>
        <div style="float: right; margin-top: 0px">
            <span class="glyphicon glyphicon-calendar"></span> Data Expirarii: <?=$this->expirationDate?>
            <span style="padding-left:10px"></span>
            <span class="glyphicon glyphicon-eye-open"></span> Vizualizari: <?=$this->views?>
            <span style="padding-left:10px"></span>
            <span class="glyphicon glyphicon-earphone"></span> Contact Afisat: <?=$this->contactDisplayed?>
        </div>
        <p><?=$this->description?></p>
        <p><?=$this->car?></p>
        <?php if ($this->status == 'expired') { ?>
        <a href="<?=$this->url('home/ad/changeStatus', ['mode'=>'activate', 'id'=>$this->id, 'token'=>$this->token])?>"
           class="btn btn-primary btn-sm" role="button">Reactiveaza Anunt</a>
        <?php } else { ?>
        <a href="<?=$this->url('home/ad/create', ['id'=>$this->id])?>" class="btn btn-success btn-sm" role="button">Modifica Anunt</a>
        <?php } ?>
        <a href="javascript:;" onclick="<?=\Application\libs\General::confirmBoxJS(
            $this,
            $this->url('home/ad/changeStatus', ['mode'=>'delete', 'id'=>$this->id, 'token'=>$this->token]),
            'Vrei sa stergi definitiv acest anunt?'
        )?>"
           class="btn btn-danger btn-sm" role="button">Sterge Anunt</a>
    </div>
</div>