<div id="categoryContainer" class="panel category-panel <?=$this->displayedOn == 'piese' ? 'category-on-piese' : ''?> row card card-2">
    <?php foreach($this->layout()->cars['categories'] as $categId => $categName) {
        $categNameUrlized = strtolower($this->carCollection->getUrlize($categName));
        if ($this->carcategoriesId == $categId) {
            $activeCategMameUrlized = strtolower($this->carCollection->getUrlize($categName));
            $activeCategName = $categName;
        }
        ?>
        <div class="col-md-2 col-sm-4 col-xs-<?=$this->displayedOn == 'piese' ? 2 : 6?> category <?=($this->carcategoriesId == $categId ? 'active' : '')?>">
            <a href="<?= $this->url('home/piese', ['categories' => $categNameUrlized]) ?>" title="Piese <?=$categName?>">
                <img class="img-responsive" src="<?=$this->basePath() . '/img/categ_'.$categId.'.png'?>"/>
                <span><?=$categName?></span>
            </a>
        </div>
    <?php } ?>
</div>