<div class="partners">
    <div class="col-md-12 col-sm-6 col-xs-6 right-pic panel card card-1">
        <a href="<?=$this->url('home/pages/partners')?>"><img class="img-responsive" src="<?=$this->basePath() . '/img/comercials-right.jpg'?>"/></a>
    </div>

    <div class="col-md-12 col-sm-6 col-xs-6 right-pic panel card card-1">
    <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
    <!-- homepage-square -->
    <ins class="adsbygoogle"
         style="display:inline-block;width:200px;height:200px"
         data-ad-client="ca-pub-5742021999220191"
         data-ad-slot="5083652054"></ins>
    <script>
        (adsbygoogle = window.adsbygoogle || []).push({});
    </script>
    </div>
</div>