<div class="partners">
    <div class="col-md-12 col-sm-6 col-xs-12 right-pic panel card card-1">
        <a href="<?=$this->url('home/pages/partners')?>">
            <img class="img-responsive" src="<?=$this->basePath() . '/img/comercials-right.jpg'?>"/></a>
    </div>

    <div class="col-md-12 col-sm-6 col-xs-12 right-pic panel card card-1"  style="text-align: center; padding: 40px 0">
        <a href="<?=$this->url('home/pages/partners')?>">
            <img class="" src="<?=$this->basePath() . '/img/logo-footer.png'?>"/>
            <br><br>devino partener Tirbox.ro!
        </a>
    </div>
</div>